//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApexCOINESB.COINSESBService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="", ConfigurationName="COINSESBService.COINSInterfacePort")]
    public interface COINSInterfacePort {
        
        [System.ServiceModel.OperationContractAttribute(Action="https://valley.coinscloud.com/cgi-bin/learn.cgi/wouesb.p?service=POESB001&namespa" +
            "ce=false", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ApexCOINESB.COINSESBService.doActionResponse doAction(ApexCOINESB.COINSESBService.doActionRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="https://valley.coinscloud.com/cgi-bin/learn.cgi/wouesb.p?service=POESB001&namespa" +
            "ce=false", ReplyAction="*")]
        System.Threading.Tasks.Task<ApexCOINESB.COINSESBService.doActionResponse> doActionAsync(ApexCOINESB.COINSESBService.doActionRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class COINSInterfaceHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string userIDField;
        
        private string fromField;
        
        private string hostNameField;
        
        private string environmentField;
        
        private System.DateTime createdField;
        
        private bool createdFieldSpecified;
        
        private string versionField;
        
        private COINSInterfaceHeaderLogin loginField;
        
        private string idField;
        
        private COINSInterfaceHeaderConfirm confirmField;
        
        private bool confirmFieldSpecified;
        
        private COINSInterfaceHeaderAction actionField;
        
        private bool actionFieldSpecified;
        
        private string entityField;
        
        private string argumentsField;
        
        private string ackIDField;
        
        private bool testMsgField;
        
        private bool testMsgFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string UserID {
            get {
                return this.userIDField;
            }
            set {
                this.userIDField = value;
                this.RaisePropertyChanged("UserID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string From {
            get {
                return this.fromField;
            }
            set {
                this.fromField = value;
                this.RaisePropertyChanged("From");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string HostName {
            get {
                return this.hostNameField;
            }
            set {
                this.hostNameField = value;
                this.RaisePropertyChanged("HostName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Environment {
            get {
                return this.environmentField;
            }
            set {
                this.environmentField = value;
                this.RaisePropertyChanged("Environment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public System.DateTime Created {
            get {
                return this.createdField;
            }
            set {
                this.createdField = value;
                this.RaisePropertyChanged("Created");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CreatedSpecified {
            get {
                return this.createdFieldSpecified;
            }
            set {
                this.createdFieldSpecified = value;
                this.RaisePropertyChanged("CreatedSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("Version");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public COINSInterfaceHeaderLogin Login {
            get {
                return this.loginField;
            }
            set {
                this.loginField = value;
                this.RaisePropertyChanged("Login");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public COINSInterfaceHeaderConfirm confirm {
            get {
                return this.confirmField;
            }
            set {
                this.confirmField = value;
                this.RaisePropertyChanged("confirm");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool confirmSpecified {
            get {
                return this.confirmFieldSpecified;
            }
            set {
                this.confirmFieldSpecified = value;
                this.RaisePropertyChanged("confirmSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public COINSInterfaceHeaderAction action {
            get {
                return this.actionField;
            }
            set {
                this.actionField = value;
                this.RaisePropertyChanged("action");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool actionSpecified {
            get {
                return this.actionFieldSpecified;
            }
            set {
                this.actionFieldSpecified = value;
                this.RaisePropertyChanged("actionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string entity {
            get {
                return this.entityField;
            }
            set {
                this.entityField = value;
                this.RaisePropertyChanged("entity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string arguments {
            get {
                return this.argumentsField;
            }
            set {
                this.argumentsField = value;
                this.RaisePropertyChanged("arguments");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ackID {
            get {
                return this.ackIDField;
            }
            set {
                this.ackIDField = value;
                this.RaisePropertyChanged("ackID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool testMsg {
            get {
                return this.testMsgField;
            }
            set {
                this.testMsgField = value;
                this.RaisePropertyChanged("testMsg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool testMsgSpecified {
            get {
                return this.testMsgFieldSpecified;
            }
            set {
                this.testMsgFieldSpecified = value;
                this.RaisePropertyChanged("testMsgSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class COINSInterfaceHeaderLogin : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string authTokenField;
        
        private string userField;
        
        private string passwordField;
        
        private uint cIDField;
        
        private bool cIDFieldSpecified;
        
        private string groupField;
        
        private string extUserField;
        
        private string extAuthField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string AuthToken {
            get {
                return this.authTokenField;
            }
            set {
                this.authTokenField = value;
                this.RaisePropertyChanged("AuthToken");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string User {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
                this.RaisePropertyChanged("User");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public uint CID {
            get {
                return this.cIDField;
            }
            set {
                this.cIDField = value;
                this.RaisePropertyChanged("CID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CIDSpecified {
            get {
                return this.cIDFieldSpecified;
            }
            set {
                this.cIDFieldSpecified = value;
                this.RaisePropertyChanged("CIDSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Group {
            get {
                return this.groupField;
            }
            set {
                this.groupField = value;
                this.RaisePropertyChanged("Group");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string extUser {
            get {
                return this.extUserField;
            }
            set {
                this.extUserField = value;
                this.RaisePropertyChanged("extUser");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string extAuth {
            get {
                return this.extAuthField;
            }
            set {
                this.extAuthField = value;
                this.RaisePropertyChanged("extAuth");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum COINSInterfaceHeaderConfirm {
        
        /// <remarks/>
        yes,
        
        /// <remarks/>
        y,
        
        /// <remarks/>
        @true,
        
        /// <remarks/>
        no,
        
        /// <remarks/>
        n,
        
        /// <remarks/>
        @false,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum COINSInterfaceHeaderAction {
        
        /// <remarks/>
        CREATE,
        
        /// <remarks/>
        DELETE,
        
        /// <remarks/>
        UPDATE,
        
        /// <remarks/>
        PUBLISH,
        
        /// <remarks/>
        ACKNOWLEDGE,
        
        /// <remarks/>
        EXCEPTION,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class COINSInterfacePo_hdrRow : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string rsp_actionField;
        
        private bool commitOrderField;
        
        private string poh_ordnoField;
        
        private string poh_votypeField;
        
        private string poh_mpoField;
        
        private string pot_typeField;
        
        private bool poh_headofficeField;
        
        private bool poh_confirmField;
        
        private string job_jobphField;
        
        private string pov_codeField;
        
        private string faw_refField;
        
        private string plt_numField;
        
        private int cim_intrefField;
        
        private bool cim_intrefFieldSpecified;
        
        private int cio_intrefField;
        
        private bool cio_intrefFieldSpecified;
        
        private string poh_accnoField;
        
        private string poh_nameField;
        
        private string poh_offnameField;
        
        private string poh_attentionField;
        
        private System.DateTime poh_odateField;
        
        private System.DateTime poh_ddateField;
        
        private bool poh_ddateFieldSpecified;
        
        private string poh_dalfField;
        
        private string poh_descField;
        
        private string pob_codeField;
        
        private string poh_specins__1Field;
        
        private string poh_specins__2Field;
        
        private bool poh_revrequiredField;
        
        private bool poh_revrequiredFieldSpecified;
        
        private string pvs_codeField;
        
        private bool poh_alwcodeField;
        
        private bool poh_alwcodeFieldSpecified;
        
        private string poh_reqdbyField;
        
        private string poh_reqnoField;
        
        private string pja_codeField;
        
        private string vat_codeField;
        
        private decimal poh_dMaxField;
        
        private bool poh_dMaxFieldSpecified;
        
        private decimal poh_retvalField;
        
        private bool poh_retvalFieldSpecified;
        
        private COINSInterfacePo_hdrRowPo_lineRow[] po_lineRowField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string rsp_action {
            get {
                return this.rsp_actionField;
            }
            set {
                this.rsp_actionField = value;
                this.RaisePropertyChanged("rsp_action");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool commitOrder {
            get {
                return this.commitOrderField;
            }
            set {
                this.commitOrderField = value;
                this.RaisePropertyChanged("commitOrder");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string poh_ordno {
            get {
                return this.poh_ordnoField;
            }
            set {
                this.poh_ordnoField = value;
                this.RaisePropertyChanged("poh_ordno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string poh_votype {
            get {
                return this.poh_votypeField;
            }
            set {
                this.poh_votypeField = value;
                this.RaisePropertyChanged("poh_votype");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string poh_mpo {
            get {
                return this.poh_mpoField;
            }
            set {
                this.poh_mpoField = value;
                this.RaisePropertyChanged("poh_mpo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string pot_type {
            get {
                return this.pot_typeField;
            }
            set {
                this.pot_typeField = value;
                this.RaisePropertyChanged("pot_type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public bool poh_headoffice {
            get {
                return this.poh_headofficeField;
            }
            set {
                this.poh_headofficeField = value;
                this.RaisePropertyChanged("poh_headoffice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public bool poh_confirm {
            get {
                return this.poh_confirmField;
            }
            set {
                this.poh_confirmField = value;
                this.RaisePropertyChanged("poh_confirm");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string job_jobph {
            get {
                return this.job_jobphField;
            }
            set {
                this.job_jobphField = value;
                this.RaisePropertyChanged("job_jobph");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string pov_code {
            get {
                return this.pov_codeField;
            }
            set {
                this.pov_codeField = value;
                this.RaisePropertyChanged("pov_code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string faw_ref {
            get {
                return this.faw_refField;
            }
            set {
                this.faw_refField = value;
                this.RaisePropertyChanged("faw_ref");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string plt_num {
            get {
                return this.plt_numField;
            }
            set {
                this.plt_numField = value;
                this.RaisePropertyChanged("plt_num");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public int cim_intref {
            get {
                return this.cim_intrefField;
            }
            set {
                this.cim_intrefField = value;
                this.RaisePropertyChanged("cim_intref");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cim_intrefSpecified {
            get {
                return this.cim_intrefFieldSpecified;
            }
            set {
                this.cim_intrefFieldSpecified = value;
                this.RaisePropertyChanged("cim_intrefSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public int cio_intref {
            get {
                return this.cio_intrefField;
            }
            set {
                this.cio_intrefField = value;
                this.RaisePropertyChanged("cio_intref");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cio_intrefSpecified {
            get {
                return this.cio_intrefFieldSpecified;
            }
            set {
                this.cio_intrefFieldSpecified = value;
                this.RaisePropertyChanged("cio_intrefSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string poh_accno {
            get {
                return this.poh_accnoField;
            }
            set {
                this.poh_accnoField = value;
                this.RaisePropertyChanged("poh_accno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string poh_name {
            get {
                return this.poh_nameField;
            }
            set {
                this.poh_nameField = value;
                this.RaisePropertyChanged("poh_name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string poh_offname {
            get {
                return this.poh_offnameField;
            }
            set {
                this.poh_offnameField = value;
                this.RaisePropertyChanged("poh_offname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string poh_attention {
            get {
                return this.poh_attentionField;
            }
            set {
                this.poh_attentionField = value;
                this.RaisePropertyChanged("poh_attention");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=18)]
        public System.DateTime poh_odate {
            get {
                return this.poh_odateField;
            }
            set {
                this.poh_odateField = value;
                this.RaisePropertyChanged("poh_odate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=19)]
        public System.DateTime poh_ddate {
            get {
                return this.poh_ddateField;
            }
            set {
                this.poh_ddateField = value;
                this.RaisePropertyChanged("poh_ddate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool poh_ddateSpecified {
            get {
                return this.poh_ddateFieldSpecified;
            }
            set {
                this.poh_ddateFieldSpecified = value;
                this.RaisePropertyChanged("poh_ddateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string poh_dalf {
            get {
                return this.poh_dalfField;
            }
            set {
                this.poh_dalfField = value;
                this.RaisePropertyChanged("poh_dalf");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string poh_desc {
            get {
                return this.poh_descField;
            }
            set {
                this.poh_descField = value;
                this.RaisePropertyChanged("poh_desc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string pob_code {
            get {
                return this.pob_codeField;
            }
            set {
                this.pob_codeField = value;
                this.RaisePropertyChanged("pob_code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public string poh_specins__1 {
            get {
                return this.poh_specins__1Field;
            }
            set {
                this.poh_specins__1Field = value;
                this.RaisePropertyChanged("poh_specins__1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public string poh_specins__2 {
            get {
                return this.poh_specins__2Field;
            }
            set {
                this.poh_specins__2Field = value;
                this.RaisePropertyChanged("poh_specins__2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public bool poh_revrequired {
            get {
                return this.poh_revrequiredField;
            }
            set {
                this.poh_revrequiredField = value;
                this.RaisePropertyChanged("poh_revrequired");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool poh_revrequiredSpecified {
            get {
                return this.poh_revrequiredFieldSpecified;
            }
            set {
                this.poh_revrequiredFieldSpecified = value;
                this.RaisePropertyChanged("poh_revrequiredSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=26)]
        public string pvs_code {
            get {
                return this.pvs_codeField;
            }
            set {
                this.pvs_codeField = value;
                this.RaisePropertyChanged("pvs_code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=27)]
        public bool poh_alwcode {
            get {
                return this.poh_alwcodeField;
            }
            set {
                this.poh_alwcodeField = value;
                this.RaisePropertyChanged("poh_alwcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool poh_alwcodeSpecified {
            get {
                return this.poh_alwcodeFieldSpecified;
            }
            set {
                this.poh_alwcodeFieldSpecified = value;
                this.RaisePropertyChanged("poh_alwcodeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=28)]
        public string poh_reqdby {
            get {
                return this.poh_reqdbyField;
            }
            set {
                this.poh_reqdbyField = value;
                this.RaisePropertyChanged("poh_reqdby");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=29)]
        public string poh_reqno {
            get {
                return this.poh_reqnoField;
            }
            set {
                this.poh_reqnoField = value;
                this.RaisePropertyChanged("poh_reqno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=30)]
        public string pja_code {
            get {
                return this.pja_codeField;
            }
            set {
                this.pja_codeField = value;
                this.RaisePropertyChanged("pja_code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=31)]
        public string vat_code {
            get {
                return this.vat_codeField;
            }
            set {
                this.vat_codeField = value;
                this.RaisePropertyChanged("vat_code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=32)]
        public decimal poh_dMax {
            get {
                return this.poh_dMaxField;
            }
            set {
                this.poh_dMaxField = value;
                this.RaisePropertyChanged("poh_dMax");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool poh_dMaxSpecified {
            get {
                return this.poh_dMaxFieldSpecified;
            }
            set {
                this.poh_dMaxFieldSpecified = value;
                this.RaisePropertyChanged("poh_dMaxSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=33)]
        public decimal poh_retval {
            get {
                return this.poh_retvalField;
            }
            set {
                this.poh_retvalField = value;
                this.RaisePropertyChanged("poh_retval");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool poh_retvalSpecified {
            get {
                return this.poh_retvalFieldSpecified;
            }
            set {
                this.poh_retvalFieldSpecified = value;
                this.RaisePropertyChanged("poh_retvalSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("po_lineRow", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=34)]
        public COINSInterfacePo_hdrRowPo_lineRow[] po_lineRow {
            get {
                return this.po_lineRowField;
            }
            set {
                this.po_lineRowField = value;
                this.RaisePropertyChanged("po_lineRow");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class COINSInterfacePo_hdrRowPo_lineRow : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string rsp_actionField;
        
        private int pol_seqField;
        
        private bool pol_seqFieldSpecified;
        
        private string pol_typeField;
        
        private string pol_codeField;
        
        private string pol_descField;
        
        private string jwb_codeField;
        
        private decimal pol_qtyField;
        
        private bool pol_qtyFieldSpecified;
        
        private string pol_uoqField;
        
        private decimal pol_priceField;
        
        private bool pol_priceFieldSpecified;
        
        private string pol_perField;
        
        private decimal pol_discField;
        
        private bool pol_discFieldSpecified;
        
        private System.DateTime pol_effdateField;
        
        private bool pol_effdateFieldSpecified;
        
        private decimal pol_famountField;
        
        private bool pol_famountFieldSpecified;
        
        private System.DateTime pol_ddateField;
        
        private bool pol_ddateFieldSpecified;
        
        private string bqr_resourceField;
        
        private string tcl_codeField;
        
        private string vat_codeField;
        
        private decimal pol_taxField;
        
        private bool pol_taxFieldSpecified;
        
        private string tpc_codeField;
        
        private int pol_wbasisField;
        
        private bool pol_wbasisFieldSpecified;
        
        private bool pol_chgholField;
        
        private bool pol_chgholFieldSpecified;
        
        private decimal pol_minhireField;
        
        private bool pol_minhireFieldSpecified;
        
        private System.DateTime pol_offhireField;
        
        private bool pol_offhireFieldSpecified;
        
        private string pol_CostHeadField;
        
        private string pol_catField;
        
        private bool pol_npa_eligibleField;
        
        private int pol_npa_cim_intrefField;
        
        private bool pol_npa_cim_intrefFieldSpecified;
        
        private string pol_barnoField;
        
        private decimal pol_gross_lengthField;
        
        private bool pol_gross_lengthFieldSpecified;
        
        private decimal pol_gross_weightField;
        
        private bool pol_gross_weightFieldSpecified;
        
        private decimal pol_net_lengthField;
        
        private bool pol_net_lengthFieldSpecified;
        
        private decimal pol_net_weightField;
        
        private bool pol_net_weightFieldSpecified;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string rsp_action {
            get {
                return this.rsp_actionField;
            }
            set {
                this.rsp_actionField = value;
                this.RaisePropertyChanged("rsp_action");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int pol_seq {
            get {
                return this.pol_seqField;
            }
            set {
                this.pol_seqField = value;
                this.RaisePropertyChanged("pol_seq");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pol_seqSpecified {
            get {
                return this.pol_seqFieldSpecified;
            }
            set {
                this.pol_seqFieldSpecified = value;
                this.RaisePropertyChanged("pol_seqSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string pol_type {
            get {
                return this.pol_typeField;
            }
            set {
                this.pol_typeField = value;
                this.RaisePropertyChanged("pol_type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string pol_code {
            get {
                return this.pol_codeField;
            }
            set {
                this.pol_codeField = value;
                this.RaisePropertyChanged("pol_code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string pol_desc {
            get {
                return this.pol_descField;
            }
            set {
                this.pol_descField = value;
                this.RaisePropertyChanged("pol_desc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string jwb_code {
            get {
                return this.jwb_codeField;
            }
            set {
                this.jwb_codeField = value;
                this.RaisePropertyChanged("jwb_code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public decimal pol_qty {
            get {
                return this.pol_qtyField;
            }
            set {
                this.pol_qtyField = value;
                this.RaisePropertyChanged("pol_qty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pol_qtySpecified {
            get {
                return this.pol_qtyFieldSpecified;
            }
            set {
                this.pol_qtyFieldSpecified = value;
                this.RaisePropertyChanged("pol_qtySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string pol_uoq {
            get {
                return this.pol_uoqField;
            }
            set {
                this.pol_uoqField = value;
                this.RaisePropertyChanged("pol_uoq");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public decimal pol_price {
            get {
                return this.pol_priceField;
            }
            set {
                this.pol_priceField = value;
                this.RaisePropertyChanged("pol_price");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pol_priceSpecified {
            get {
                return this.pol_priceFieldSpecified;
            }
            set {
                this.pol_priceFieldSpecified = value;
                this.RaisePropertyChanged("pol_priceSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string pol_per {
            get {
                return this.pol_perField;
            }
            set {
                this.pol_perField = value;
                this.RaisePropertyChanged("pol_per");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public decimal pol_disc {
            get {
                return this.pol_discField;
            }
            set {
                this.pol_discField = value;
                this.RaisePropertyChanged("pol_disc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pol_discSpecified {
            get {
                return this.pol_discFieldSpecified;
            }
            set {
                this.pol_discFieldSpecified = value;
                this.RaisePropertyChanged("pol_discSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=11)]
        public System.DateTime pol_effdate {
            get {
                return this.pol_effdateField;
            }
            set {
                this.pol_effdateField = value;
                this.RaisePropertyChanged("pol_effdate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pol_effdateSpecified {
            get {
                return this.pol_effdateFieldSpecified;
            }
            set {
                this.pol_effdateFieldSpecified = value;
                this.RaisePropertyChanged("pol_effdateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public decimal pol_famount {
            get {
                return this.pol_famountField;
            }
            set {
                this.pol_famountField = value;
                this.RaisePropertyChanged("pol_famount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pol_famountSpecified {
            get {
                return this.pol_famountFieldSpecified;
            }
            set {
                this.pol_famountFieldSpecified = value;
                this.RaisePropertyChanged("pol_famountSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=13)]
        public System.DateTime pol_ddate {
            get {
                return this.pol_ddateField;
            }
            set {
                this.pol_ddateField = value;
                this.RaisePropertyChanged("pol_ddate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pol_ddateSpecified {
            get {
                return this.pol_ddateFieldSpecified;
            }
            set {
                this.pol_ddateFieldSpecified = value;
                this.RaisePropertyChanged("pol_ddateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string bqr_resource {
            get {
                return this.bqr_resourceField;
            }
            set {
                this.bqr_resourceField = value;
                this.RaisePropertyChanged("bqr_resource");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string tcl_code {
            get {
                return this.tcl_codeField;
            }
            set {
                this.tcl_codeField = value;
                this.RaisePropertyChanged("tcl_code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string vat_code {
            get {
                return this.vat_codeField;
            }
            set {
                this.vat_codeField = value;
                this.RaisePropertyChanged("vat_code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public decimal pol_tax {
            get {
                return this.pol_taxField;
            }
            set {
                this.pol_taxField = value;
                this.RaisePropertyChanged("pol_tax");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pol_taxSpecified {
            get {
                return this.pol_taxFieldSpecified;
            }
            set {
                this.pol_taxFieldSpecified = value;
                this.RaisePropertyChanged("pol_taxSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string tpc_code {
            get {
                return this.tpc_codeField;
            }
            set {
                this.tpc_codeField = value;
                this.RaisePropertyChanged("tpc_code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public int pol_wbasis {
            get {
                return this.pol_wbasisField;
            }
            set {
                this.pol_wbasisField = value;
                this.RaisePropertyChanged("pol_wbasis");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pol_wbasisSpecified {
            get {
                return this.pol_wbasisFieldSpecified;
            }
            set {
                this.pol_wbasisFieldSpecified = value;
                this.RaisePropertyChanged("pol_wbasisSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public bool pol_chghol {
            get {
                return this.pol_chgholField;
            }
            set {
                this.pol_chgholField = value;
                this.RaisePropertyChanged("pol_chghol");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pol_chgholSpecified {
            get {
                return this.pol_chgholFieldSpecified;
            }
            set {
                this.pol_chgholFieldSpecified = value;
                this.RaisePropertyChanged("pol_chgholSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public decimal pol_minhire {
            get {
                return this.pol_minhireField;
            }
            set {
                this.pol_minhireField = value;
                this.RaisePropertyChanged("pol_minhire");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pol_minhireSpecified {
            get {
                return this.pol_minhireFieldSpecified;
            }
            set {
                this.pol_minhireFieldSpecified = value;
                this.RaisePropertyChanged("pol_minhireSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=22)]
        public System.DateTime pol_offhire {
            get {
                return this.pol_offhireField;
            }
            set {
                this.pol_offhireField = value;
                this.RaisePropertyChanged("pol_offhire");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pol_offhireSpecified {
            get {
                return this.pol_offhireFieldSpecified;
            }
            set {
                this.pol_offhireFieldSpecified = value;
                this.RaisePropertyChanged("pol_offhireSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public string pol_CostHead {
            get {
                return this.pol_CostHeadField;
            }
            set {
                this.pol_CostHeadField = value;
                this.RaisePropertyChanged("pol_CostHead");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public string pol_cat {
            get {
                return this.pol_catField;
            }
            set {
                this.pol_catField = value;
                this.RaisePropertyChanged("pol_cat");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public bool pol_npa_eligible {
            get {
                return this.pol_npa_eligibleField;
            }
            set {
                this.pol_npa_eligibleField = value;
                this.RaisePropertyChanged("pol_npa_eligible");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=26)]
        public int pol_npa_cim_intref {
            get {
                return this.pol_npa_cim_intrefField;
            }
            set {
                this.pol_npa_cim_intrefField = value;
                this.RaisePropertyChanged("pol_npa_cim_intref");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pol_npa_cim_intrefSpecified {
            get {
                return this.pol_npa_cim_intrefFieldSpecified;
            }
            set {
                this.pol_npa_cim_intrefFieldSpecified = value;
                this.RaisePropertyChanged("pol_npa_cim_intrefSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=27)]
        public string pol_barno {
            get {
                return this.pol_barnoField;
            }
            set {
                this.pol_barnoField = value;
                this.RaisePropertyChanged("pol_barno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=28)]
        public decimal pol_gross_length {
            get {
                return this.pol_gross_lengthField;
            }
            set {
                this.pol_gross_lengthField = value;
                this.RaisePropertyChanged("pol_gross_length");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pol_gross_lengthSpecified {
            get {
                return this.pol_gross_lengthFieldSpecified;
            }
            set {
                this.pol_gross_lengthFieldSpecified = value;
                this.RaisePropertyChanged("pol_gross_lengthSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=29)]
        public decimal pol_gross_weight {
            get {
                return this.pol_gross_weightField;
            }
            set {
                this.pol_gross_weightField = value;
                this.RaisePropertyChanged("pol_gross_weight");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pol_gross_weightSpecified {
            get {
                return this.pol_gross_weightFieldSpecified;
            }
            set {
                this.pol_gross_weightFieldSpecified = value;
                this.RaisePropertyChanged("pol_gross_weightSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=30)]
        public decimal pol_net_length {
            get {
                return this.pol_net_lengthField;
            }
            set {
                this.pol_net_lengthField = value;
                this.RaisePropertyChanged("pol_net_length");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pol_net_lengthSpecified {
            get {
                return this.pol_net_lengthFieldSpecified;
            }
            set {
                this.pol_net_lengthFieldSpecified = value;
                this.RaisePropertyChanged("pol_net_lengthSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=31)]
        public decimal pol_net_weight {
            get {
                return this.pol_net_weightField;
            }
            set {
                this.pol_net_weightField = value;
                this.RaisePropertyChanged("pol_net_weight");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pol_net_weightSpecified {
            get {
                return this.pol_net_weightFieldSpecified;
            }
            set {
                this.pol_net_weightFieldSpecified = value;
                this.RaisePropertyChanged("pol_net_weightSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class COINSInterfaceResponseHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string userIDField;
        
        private string fromField;
        
        private string hostNameField;
        
        private string environmentField;
        
        private System.DateTime createdField;
        
        private bool createdFieldSpecified;
        
        private string versionField;
        
        private string schemaVersionField;
        
        private string objectField;
        
        private string idField;
        
        private COINSInterfaceResponseHeaderConfirm confirmField;
        
        private bool confirmFieldSpecified;
        
        private COINSInterfaceResponseHeaderAction actionField;
        
        private bool actionFieldSpecified;
        
        private string entityField;
        
        private string ackIDField;
        
        private bool initialiseField;
        
        private bool initialiseFieldSpecified;
        
        private int initCountField;
        
        private bool initCountFieldSpecified;
        
        private int sin_refField;
        
        private bool sin_refFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string UserID {
            get {
                return this.userIDField;
            }
            set {
                this.userIDField = value;
                this.RaisePropertyChanged("UserID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string From {
            get {
                return this.fromField;
            }
            set {
                this.fromField = value;
                this.RaisePropertyChanged("From");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string HostName {
            get {
                return this.hostNameField;
            }
            set {
                this.hostNameField = value;
                this.RaisePropertyChanged("HostName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Environment {
            get {
                return this.environmentField;
            }
            set {
                this.environmentField = value;
                this.RaisePropertyChanged("Environment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public System.DateTime Created {
            get {
                return this.createdField;
            }
            set {
                this.createdField = value;
                this.RaisePropertyChanged("Created");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CreatedSpecified {
            get {
                return this.createdFieldSpecified;
            }
            set {
                this.createdFieldSpecified = value;
                this.RaisePropertyChanged("CreatedSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("Version");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string SchemaVersion {
            get {
                return this.schemaVersionField;
            }
            set {
                this.schemaVersionField = value;
                this.RaisePropertyChanged("SchemaVersion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string Object {
            get {
                return this.objectField;
            }
            set {
                this.objectField = value;
                this.RaisePropertyChanged("Object");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public COINSInterfaceResponseHeaderConfirm confirm {
            get {
                return this.confirmField;
            }
            set {
                this.confirmField = value;
                this.RaisePropertyChanged("confirm");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool confirmSpecified {
            get {
                return this.confirmFieldSpecified;
            }
            set {
                this.confirmFieldSpecified = value;
                this.RaisePropertyChanged("confirmSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public COINSInterfaceResponseHeaderAction action {
            get {
                return this.actionField;
            }
            set {
                this.actionField = value;
                this.RaisePropertyChanged("action");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool actionSpecified {
            get {
                return this.actionFieldSpecified;
            }
            set {
                this.actionFieldSpecified = value;
                this.RaisePropertyChanged("actionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string entity {
            get {
                return this.entityField;
            }
            set {
                this.entityField = value;
                this.RaisePropertyChanged("entity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ackID {
            get {
                return this.ackIDField;
            }
            set {
                this.ackIDField = value;
                this.RaisePropertyChanged("ackID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool initialise {
            get {
                return this.initialiseField;
            }
            set {
                this.initialiseField = value;
                this.RaisePropertyChanged("initialise");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool initialiseSpecified {
            get {
                return this.initialiseFieldSpecified;
            }
            set {
                this.initialiseFieldSpecified = value;
                this.RaisePropertyChanged("initialiseSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int initCount {
            get {
                return this.initCountField;
            }
            set {
                this.initCountField = value;
                this.RaisePropertyChanged("initCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool initCountSpecified {
            get {
                return this.initCountFieldSpecified;
            }
            set {
                this.initCountFieldSpecified = value;
                this.RaisePropertyChanged("initCountSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int sin_ref {
            get {
                return this.sin_refField;
            }
            set {
                this.sin_refField = value;
                this.RaisePropertyChanged("sin_ref");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sin_refSpecified {
            get {
                return this.sin_refFieldSpecified;
            }
            set {
                this.sin_refFieldSpecified = value;
                this.RaisePropertyChanged("sin_refSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum COINSInterfaceResponseHeaderConfirm {
        
        /// <remarks/>
        yes,
        
        /// <remarks/>
        y,
        
        /// <remarks/>
        @true,
        
        /// <remarks/>
        no,
        
        /// <remarks/>
        n,
        
        /// <remarks/>
        @false,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum COINSInterfaceResponseHeaderAction {
        
        /// <remarks/>
        CREATE,
        
        /// <remarks/>
        DELETE,
        
        /// <remarks/>
        UPDATE,
        
        /// <remarks/>
        PUBLISH,
        
        /// <remarks/>
        ACKNOWLEDGE,
        
        /// <remarks/>
        RESPONSE,
        
        /// <remarks/>
        EXCEPTION,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class COINSInterfaceResponseBody : object, System.ComponentModel.INotifyPropertyChanged {
        
        private COINSInterfaceResponseBodyException exceptionField;
        
        private COINSInterfaceResponseBodyPo_hdrRow[] po_hdrRowField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public COINSInterfaceResponseBodyException Exception {
            get {
                return this.exceptionField;
            }
            set {
                this.exceptionField = value;
                this.RaisePropertyChanged("Exception");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("po_hdrRow", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public COINSInterfaceResponseBodyPo_hdrRow[] po_hdrRow {
            get {
                return this.po_hdrRowField;
            }
            set {
                this.po_hdrRowField = value;
                this.RaisePropertyChanged("po_hdrRow");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class COINSInterfaceResponseBodyException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string exceptionField;
        
        private string thrownAtField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Exception {
            get {
                return this.exceptionField;
            }
            set {
                this.exceptionField = value;
                this.RaisePropertyChanged("Exception");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ThrownAt {
            get {
                return this.thrownAtField;
            }
            set {
                this.thrownAtField = value;
                this.RaisePropertyChanged("ThrownAt");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class COINSInterfaceResponseBodyPo_hdrRow : object, System.ComponentModel.INotifyPropertyChanged {
        
        private COINSInterfaceResponseBodyPo_hdrRowPo_lineRow[] po_lineRowField;
        
        private string poh_ordnoField;
        
        private string poh_chgnoField;
        
        private string poh_appstatField;
        
        private string poh_committedField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("po_lineRow", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public COINSInterfaceResponseBodyPo_hdrRowPo_lineRow[] po_lineRow {
            get {
                return this.po_lineRowField;
            }
            set {
                this.po_lineRowField = value;
                this.RaisePropertyChanged("po_lineRow");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string poh_ordno {
            get {
                return this.poh_ordnoField;
            }
            set {
                this.poh_ordnoField = value;
                this.RaisePropertyChanged("poh_ordno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string poh_chgno {
            get {
                return this.poh_chgnoField;
            }
            set {
                this.poh_chgnoField = value;
                this.RaisePropertyChanged("poh_chgno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string poh_appstat {
            get {
                return this.poh_appstatField;
            }
            set {
                this.poh_appstatField = value;
                this.RaisePropertyChanged("poh_appstat");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string poh_committed {
            get {
                return this.poh_committedField;
            }
            set {
                this.poh_committedField = value;
                this.RaisePropertyChanged("poh_committed");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class COINSInterfaceResponseBodyPo_hdrRowPo_lineRow : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int pol_seqField;
        
        private bool pol_seqFieldSpecified;
        
        private string pol_typeField;
        
        private string poi_itemField;
        
        private string pol_codeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int pol_seq {
            get {
                return this.pol_seqField;
            }
            set {
                this.pol_seqField = value;
                this.RaisePropertyChanged("pol_seq");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pol_seqSpecified {
            get {
                return this.pol_seqFieldSpecified;
            }
            set {
                this.pol_seqFieldSpecified = value;
                this.RaisePropertyChanged("pol_seqSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string pol_type {
            get {
                return this.pol_typeField;
            }
            set {
                this.pol_typeField = value;
                this.RaisePropertyChanged("pol_type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string poi_item {
            get {
                return this.poi_itemField;
            }
            set {
                this.poi_itemField = value;
                this.RaisePropertyChanged("poi_item");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string pol_code {
            get {
                return this.pol_codeField;
            }
            set {
                this.pol_codeField = value;
                this.RaisePropertyChanged("pol_code");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="COINSInterface", WrapperNamespace="", IsWrapped=true)]
    public partial class doActionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ApexCOINESB.COINSESBService.COINSInterfaceHeader Header;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("po_hdrRow", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ApexCOINESB.COINSESBService.COINSInterfacePo_hdrRow[] Body;
        
        public doActionRequest() {
        }
        
        public doActionRequest(ApexCOINESB.COINSESBService.COINSInterfaceHeader Header, ApexCOINESB.COINSESBService.COINSInterfacePo_hdrRow[] Body) {
            this.Header = Header;
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="COINSInterfaceResponse", WrapperNamespace="", IsWrapped=true)]
    public partial class doActionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ApexCOINESB.COINSESBService.COINSInterfaceResponseHeader Header;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ApexCOINESB.COINSESBService.COINSInterfaceResponseBody Body;
        
        public doActionResponse() {
        }
        
        public doActionResponse(ApexCOINESB.COINSESBService.COINSInterfaceResponseHeader Header, ApexCOINESB.COINSESBService.COINSInterfaceResponseBody Body) {
            this.Header = Header;
            this.Body = Body;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface COINSInterfacePortChannel : ApexCOINESB.COINSESBService.COINSInterfacePort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class COINSInterfacePortClient : System.ServiceModel.ClientBase<ApexCOINESB.COINSESBService.COINSInterfacePort>, ApexCOINESB.COINSESBService.COINSInterfacePort {
        
        public COINSInterfacePortClient() {
        }
        
        public COINSInterfacePortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public COINSInterfacePortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public COINSInterfacePortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public COINSInterfacePortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ApexCOINESB.COINSESBService.doActionResponse ApexCOINESB.COINSESBService.COINSInterfacePort.doAction(ApexCOINESB.COINSESBService.doActionRequest request) {
            return base.Channel.doAction(request);
        }
        
        public ApexCOINESB.COINSESBService.COINSInterfaceResponseHeader doAction(ApexCOINESB.COINSESBService.COINSInterfaceHeader Header, ApexCOINESB.COINSESBService.COINSInterfacePo_hdrRow[] Body, out ApexCOINESB.COINSESBService.COINSInterfaceResponseBody Body1) {
            ApexCOINESB.COINSESBService.doActionRequest inValue = new ApexCOINESB.COINSESBService.doActionRequest();
            inValue.Header = Header;
            inValue.Body = Body;
            ApexCOINESB.COINSESBService.doActionResponse retVal = ((ApexCOINESB.COINSESBService.COINSInterfacePort)(this)).doAction(inValue);
            Body1 = retVal.Body;
            return retVal.Header;
        }
        
        public System.Threading.Tasks.Task<ApexCOINESB.COINSESBService.doActionResponse> doActionAsync(ApexCOINESB.COINSESBService.doActionRequest request) {
            return base.Channel.doActionAsync(request);
        }
    }
}
