#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApexCOINESB
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ApexVEC")]
	public partial class ApexDataDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertPO(PO instance);
    partial void UpdatePO(PO instance);
    partial void DeletePO(PO instance);
    partial void InsertPOLine(POLine instance);
    partial void UpdatePOLine(POLine instance);
    partial void DeletePOLine(POLine instance);
    partial void InsertCOINSESB_WB(COINSESB_WB instance);
    partial void UpdateCOINSESB_WB(COINSESB_WB instance);
    partial void DeleteCOINSESB_WB(COINSESB_WB instance);
    partial void InsertContact(Contact instance);
    partial void UpdateContact(Contact instance);
    partial void DeleteContact(Contact instance);
    partial void InsertApexSystem(ApexSystem instance);
    partial void UpdateApexSystem(ApexSystem instance);
    partial void DeleteApexSystem(ApexSystem instance);
    partial void InsertJob(Job instance);
    partial void UpdateJob(Job instance);
    partial void DeleteJob(Job instance);
    partial void InsertCostcode(Costcode instance);
    partial void UpdateCostcode(Costcode instance);
    partial void DeleteCostcode(Costcode instance);
    partial void InsertCOINSESB_ExpL(COINSESB_ExpL instance);
    partial void UpdateCOINSESB_ExpL(COINSESB_ExpL instance);
    partial void DeleteCOINSESB_ExpL(COINSESB_ExpL instance);
    #endregion
		
		public ApexDataDataContext() : 
				base(global::ApexCOINESB.Properties.Settings.Default.ApexVECConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ApexDataDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ApexDataDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ApexDataDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ApexDataDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<PO> POs
		{
			get
			{
				return this.GetTable<PO>();
			}
		}
		
		public System.Data.Linq.Table<POLine> POLines
		{
			get
			{
				return this.GetTable<POLine>();
			}
		}
		
		public System.Data.Linq.Table<COINSESB_WB> COINSESB_WBs
		{
			get
			{
				return this.GetTable<COINSESB_WB>();
			}
		}
		
		public System.Data.Linq.Table<Contact> Contacts
		{
			get
			{
				return this.GetTable<Contact>();
			}
		}
		
		public System.Data.Linq.Table<ApexSystem> ApexSystems
		{
			get
			{
				return this.GetTable<ApexSystem>();
			}
		}
		
		public System.Data.Linq.Table<Job> Jobs
		{
			get
			{
				return this.GetTable<Job>();
			}
		}
		
		public System.Data.Linq.Table<Costcode> Costcodes
		{
			get
			{
				return this.GetTable<Costcode>();
			}
		}
		
		public System.Data.Linq.Table<COINSESB_ExpL> COINSESB_ExpLs
		{
			get
			{
				return this.GetTable<COINSESB_ExpL>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PO")]
	public partial class PO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Po1;
		
		private string _Vendor;
		
		private string _VendorName;
		
		private string _VendorAdd1;
		
		private string _VendorAdd2;
		
		private string _VendorCity;
		
		private string _VendorState;
		
		private string _VendorZip;
		
		private string _VendorAttn;
		
		private string _VendorPhone;
		
		private string _VendorTerms;
		
		private System.Nullable<System.DateTime> _EntDate;
		
		private string _Buyer;
		
		private string _Via;
		
		private string _Fob;
		
		private System.Nullable<decimal> _PoNet;
		
		private System.Nullable<decimal> _PoTax;
		
		private System.Nullable<decimal> _PoGross;
		
		private string _PriceCol;
		
		private string _Job;
		
		private string _JobPhase;
		
		private System.Nullable<System.DateTime> _ShipDate;
		
		private string _Name;
		
		private string _Add1;
		
		private string _Add2;
		
		private string _City;
		
		private string _State;
		
		private string _Zip;
		
		private string _Attn;
		
		private string _Phone;
		
		private string _WorkOrd;
		
		private System.Nullable<int> _ExpBatch;
		
		private string _ExpSent;
		
		private System.Nullable<double> _TaxRate;
		
		private string _Requisition;
		
		private string _Company;
		
		private string _Division;
		
		private string _POStatus;
		
		private string _PODesc;
		
		private string _ContactID;
		
		private EntitySet<POLine> _POLines;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPo1Changing(string value);
    partial void OnPo1Changed();
    partial void OnVendorChanging(string value);
    partial void OnVendorChanged();
    partial void OnVendorNameChanging(string value);
    partial void OnVendorNameChanged();
    partial void OnVendorAdd1Changing(string value);
    partial void OnVendorAdd1Changed();
    partial void OnVendorAdd2Changing(string value);
    partial void OnVendorAdd2Changed();
    partial void OnVendorCityChanging(string value);
    partial void OnVendorCityChanged();
    partial void OnVendorStateChanging(string value);
    partial void OnVendorStateChanged();
    partial void OnVendorZipChanging(string value);
    partial void OnVendorZipChanged();
    partial void OnVendorAttnChanging(string value);
    partial void OnVendorAttnChanged();
    partial void OnVendorPhoneChanging(string value);
    partial void OnVendorPhoneChanged();
    partial void OnVendorTermsChanging(string value);
    partial void OnVendorTermsChanged();
    partial void OnEntDateChanging(System.Nullable<System.DateTime> value);
    partial void OnEntDateChanged();
    partial void OnBuyerChanging(string value);
    partial void OnBuyerChanged();
    partial void OnViaChanging(string value);
    partial void OnViaChanged();
    partial void OnFobChanging(string value);
    partial void OnFobChanged();
    partial void OnPoNetChanging(System.Nullable<decimal> value);
    partial void OnPoNetChanged();
    partial void OnPoTaxChanging(System.Nullable<decimal> value);
    partial void OnPoTaxChanged();
    partial void OnPoGrossChanging(System.Nullable<decimal> value);
    partial void OnPoGrossChanged();
    partial void OnPriceColChanging(string value);
    partial void OnPriceColChanged();
    partial void OnJobChanging(string value);
    partial void OnJobChanged();
    partial void OnJobPhaseChanging(string value);
    partial void OnJobPhaseChanged();
    partial void OnShipDateChanging(System.Nullable<System.DateTime> value);
    partial void OnShipDateChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnAdd1Changing(string value);
    partial void OnAdd1Changed();
    partial void OnAdd2Changing(string value);
    partial void OnAdd2Changed();
    partial void OnCityChanging(string value);
    partial void OnCityChanged();
    partial void OnStateChanging(string value);
    partial void OnStateChanged();
    partial void OnZipChanging(string value);
    partial void OnZipChanged();
    partial void OnAttnChanging(string value);
    partial void OnAttnChanged();
    partial void OnPhoneChanging(string value);
    partial void OnPhoneChanged();
    partial void OnWorkOrdChanging(string value);
    partial void OnWorkOrdChanged();
    partial void OnExpBatchChanging(System.Nullable<int> value);
    partial void OnExpBatchChanged();
    partial void OnExpSentChanging(string value);
    partial void OnExpSentChanged();
    partial void OnTaxRateChanging(System.Nullable<double> value);
    partial void OnTaxRateChanged();
    partial void OnRequisitionChanging(string value);
    partial void OnRequisitionChanged();
    partial void OnCompanyChanging(string value);
    partial void OnCompanyChanged();
    partial void OnDivisionChanging(string value);
    partial void OnDivisionChanged();
    partial void OnPOStatusChanging(string value);
    partial void OnPOStatusChanged();
    partial void OnPODescChanging(string value);
    partial void OnPODescChanged();
    partial void OnContactIDChanging(string value);
    partial void OnContactIDChanged();
    #endregion
		
		public PO()
		{
			this._POLines = new EntitySet<POLine>(new Action<POLine>(this.attach_POLines), new Action<POLine>(this.detach_POLines));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Po", Storage="_Po1", DbType="VarChar(12) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Po1
		{
			get
			{
				return this._Po1;
			}
			set
			{
				if ((this._Po1 != value))
				{
					this.OnPo1Changing(value);
					this.SendPropertyChanging();
					this._Po1 = value;
					this.SendPropertyChanged("Po1");
					this.OnPo1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vendor", DbType="VarChar(6)")]
		public string Vendor
		{
			get
			{
				return this._Vendor;
			}
			set
			{
				if ((this._Vendor != value))
				{
					this.OnVendorChanging(value);
					this.SendPropertyChanging();
					this._Vendor = value;
					this.SendPropertyChanged("Vendor");
					this.OnVendorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VendorName", DbType="VarChar(25)")]
		public string VendorName
		{
			get
			{
				return this._VendorName;
			}
			set
			{
				if ((this._VendorName != value))
				{
					this.OnVendorNameChanging(value);
					this.SendPropertyChanging();
					this._VendorName = value;
					this.SendPropertyChanged("VendorName");
					this.OnVendorNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VendorAdd1", DbType="VarChar(25)")]
		public string VendorAdd1
		{
			get
			{
				return this._VendorAdd1;
			}
			set
			{
				if ((this._VendorAdd1 != value))
				{
					this.OnVendorAdd1Changing(value);
					this.SendPropertyChanging();
					this._VendorAdd1 = value;
					this.SendPropertyChanged("VendorAdd1");
					this.OnVendorAdd1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VendorAdd2", DbType="VarChar(25)")]
		public string VendorAdd2
		{
			get
			{
				return this._VendorAdd2;
			}
			set
			{
				if ((this._VendorAdd2 != value))
				{
					this.OnVendorAdd2Changing(value);
					this.SendPropertyChanging();
					this._VendorAdd2 = value;
					this.SendPropertyChanged("VendorAdd2");
					this.OnVendorAdd2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VendorCity", DbType="VarChar(15)")]
		public string VendorCity
		{
			get
			{
				return this._VendorCity;
			}
			set
			{
				if ((this._VendorCity != value))
				{
					this.OnVendorCityChanging(value);
					this.SendPropertyChanging();
					this._VendorCity = value;
					this.SendPropertyChanged("VendorCity");
					this.OnVendorCityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VendorState", DbType="VarChar(4)")]
		public string VendorState
		{
			get
			{
				return this._VendorState;
			}
			set
			{
				if ((this._VendorState != value))
				{
					this.OnVendorStateChanging(value);
					this.SendPropertyChanging();
					this._VendorState = value;
					this.SendPropertyChanged("VendorState");
					this.OnVendorStateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VendorZip", DbType="VarChar(15)")]
		public string VendorZip
		{
			get
			{
				return this._VendorZip;
			}
			set
			{
				if ((this._VendorZip != value))
				{
					this.OnVendorZipChanging(value);
					this.SendPropertyChanging();
					this._VendorZip = value;
					this.SendPropertyChanged("VendorZip");
					this.OnVendorZipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VendorAttn", DbType="VarChar(20)")]
		public string VendorAttn
		{
			get
			{
				return this._VendorAttn;
			}
			set
			{
				if ((this._VendorAttn != value))
				{
					this.OnVendorAttnChanging(value);
					this.SendPropertyChanging();
					this._VendorAttn = value;
					this.SendPropertyChanged("VendorAttn");
					this.OnVendorAttnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VendorPhone", DbType="VarChar(15)")]
		public string VendorPhone
		{
			get
			{
				return this._VendorPhone;
			}
			set
			{
				if ((this._VendorPhone != value))
				{
					this.OnVendorPhoneChanging(value);
					this.SendPropertyChanging();
					this._VendorPhone = value;
					this.SendPropertyChanged("VendorPhone");
					this.OnVendorPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VendorTerms", DbType="VarChar(15)")]
		public string VendorTerms
		{
			get
			{
				return this._VendorTerms;
			}
			set
			{
				if ((this._VendorTerms != value))
				{
					this.OnVendorTermsChanging(value);
					this.SendPropertyChanging();
					this._VendorTerms = value;
					this.SendPropertyChanged("VendorTerms");
					this.OnVendorTermsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EntDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> EntDate
		{
			get
			{
				return this._EntDate;
			}
			set
			{
				if ((this._EntDate != value))
				{
					this.OnEntDateChanging(value);
					this.SendPropertyChanging();
					this._EntDate = value;
					this.SendPropertyChanged("EntDate");
					this.OnEntDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Buyer", DbType="VarChar(3)")]
		public string Buyer
		{
			get
			{
				return this._Buyer;
			}
			set
			{
				if ((this._Buyer != value))
				{
					this.OnBuyerChanging(value);
					this.SendPropertyChanging();
					this._Buyer = value;
					this.SendPropertyChanged("Buyer");
					this.OnBuyerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Via", DbType="VarChar(15)")]
		public string Via
		{
			get
			{
				return this._Via;
			}
			set
			{
				if ((this._Via != value))
				{
					this.OnViaChanging(value);
					this.SendPropertyChanging();
					this._Via = value;
					this.SendPropertyChanged("Via");
					this.OnViaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fob", DbType="VarChar(15)")]
		public string Fob
		{
			get
			{
				return this._Fob;
			}
			set
			{
				if ((this._Fob != value))
				{
					this.OnFobChanging(value);
					this.SendPropertyChanging();
					this._Fob = value;
					this.SendPropertyChanged("Fob");
					this.OnFobChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PoNet", DbType="Money")]
		public System.Nullable<decimal> PoNet
		{
			get
			{
				return this._PoNet;
			}
			set
			{
				if ((this._PoNet != value))
				{
					this.OnPoNetChanging(value);
					this.SendPropertyChanging();
					this._PoNet = value;
					this.SendPropertyChanged("PoNet");
					this.OnPoNetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PoTax", DbType="Money")]
		public System.Nullable<decimal> PoTax
		{
			get
			{
				return this._PoTax;
			}
			set
			{
				if ((this._PoTax != value))
				{
					this.OnPoTaxChanging(value);
					this.SendPropertyChanging();
					this._PoTax = value;
					this.SendPropertyChanged("PoTax");
					this.OnPoTaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PoGross", DbType="Money")]
		public System.Nullable<decimal> PoGross
		{
			get
			{
				return this._PoGross;
			}
			set
			{
				if ((this._PoGross != value))
				{
					this.OnPoGrossChanging(value);
					this.SendPropertyChanging();
					this._PoGross = value;
					this.SendPropertyChanged("PoGross");
					this.OnPoGrossChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PriceCol", DbType="VarChar(1)")]
		public string PriceCol
		{
			get
			{
				return this._PriceCol;
			}
			set
			{
				if ((this._PriceCol != value))
				{
					this.OnPriceColChanging(value);
					this.SendPropertyChanging();
					this._PriceCol = value;
					this.SendPropertyChanged("PriceCol");
					this.OnPriceColChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Job", DbType="VarChar(12)")]
		public string Job
		{
			get
			{
				return this._Job;
			}
			set
			{
				if ((this._Job != value))
				{
					this.OnJobChanging(value);
					this.SendPropertyChanging();
					this._Job = value;
					this.SendPropertyChanged("Job");
					this.OnJobChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JobPhase", DbType="VarChar(2)")]
		public string JobPhase
		{
			get
			{
				return this._JobPhase;
			}
			set
			{
				if ((this._JobPhase != value))
				{
					this.OnJobPhaseChanging(value);
					this.SendPropertyChanging();
					this._JobPhase = value;
					this.SendPropertyChanged("JobPhase");
					this.OnJobPhaseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShipDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ShipDate
		{
			get
			{
				return this._ShipDate;
			}
			set
			{
				if ((this._ShipDate != value))
				{
					this.OnShipDateChanging(value);
					this.SendPropertyChanging();
					this._ShipDate = value;
					this.SendPropertyChanged("ShipDate");
					this.OnShipDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(25)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Add1", DbType="VarChar(25)")]
		public string Add1
		{
			get
			{
				return this._Add1;
			}
			set
			{
				if ((this._Add1 != value))
				{
					this.OnAdd1Changing(value);
					this.SendPropertyChanging();
					this._Add1 = value;
					this.SendPropertyChanged("Add1");
					this.OnAdd1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Add2", DbType="VarChar(25)")]
		public string Add2
		{
			get
			{
				return this._Add2;
			}
			set
			{
				if ((this._Add2 != value))
				{
					this.OnAdd2Changing(value);
					this.SendPropertyChanging();
					this._Add2 = value;
					this.SendPropertyChanged("Add2");
					this.OnAdd2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="VarChar(15)")]
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				if ((this._City != value))
				{
					this.OnCityChanging(value);
					this.SendPropertyChanging();
					this._City = value;
					this.SendPropertyChanged("City");
					this.OnCityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State", DbType="VarChar(4)")]
		public string State
		{
			get
			{
				return this._State;
			}
			set
			{
				if ((this._State != value))
				{
					this.OnStateChanging(value);
					this.SendPropertyChanging();
					this._State = value;
					this.SendPropertyChanged("State");
					this.OnStateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zip", DbType="VarChar(15)")]
		public string Zip
		{
			get
			{
				return this._Zip;
			}
			set
			{
				if ((this._Zip != value))
				{
					this.OnZipChanging(value);
					this.SendPropertyChanging();
					this._Zip = value;
					this.SendPropertyChanged("Zip");
					this.OnZipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Attn", DbType="VarChar(20)")]
		public string Attn
		{
			get
			{
				return this._Attn;
			}
			set
			{
				if ((this._Attn != value))
				{
					this.OnAttnChanging(value);
					this.SendPropertyChanging();
					this._Attn = value;
					this.SendPropertyChanged("Attn");
					this.OnAttnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="VarChar(15)")]
		public string Phone
		{
			get
			{
				return this._Phone;
			}
			set
			{
				if ((this._Phone != value))
				{
					this.OnPhoneChanging(value);
					this.SendPropertyChanging();
					this._Phone = value;
					this.SendPropertyChanged("Phone");
					this.OnPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WorkOrd", DbType="VarChar(12)")]
		public string WorkOrd
		{
			get
			{
				return this._WorkOrd;
			}
			set
			{
				if ((this._WorkOrd != value))
				{
					this.OnWorkOrdChanging(value);
					this.SendPropertyChanging();
					this._WorkOrd = value;
					this.SendPropertyChanged("WorkOrd");
					this.OnWorkOrdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExpBatch", DbType="Int")]
		public System.Nullable<int> ExpBatch
		{
			get
			{
				return this._ExpBatch;
			}
			set
			{
				if ((this._ExpBatch != value))
				{
					this.OnExpBatchChanging(value);
					this.SendPropertyChanging();
					this._ExpBatch = value;
					this.SendPropertyChanged("ExpBatch");
					this.OnExpBatchChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExpSent", DbType="VarChar(1)")]
		public string ExpSent
		{
			get
			{
				return this._ExpSent;
			}
			set
			{
				if ((this._ExpSent != value))
				{
					this.OnExpSentChanging(value);
					this.SendPropertyChanging();
					this._ExpSent = value;
					this.SendPropertyChanged("ExpSent");
					this.OnExpSentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaxRate", DbType="Float")]
		public System.Nullable<double> TaxRate
		{
			get
			{
				return this._TaxRate;
			}
			set
			{
				if ((this._TaxRate != value))
				{
					this.OnTaxRateChanging(value);
					this.SendPropertyChanging();
					this._TaxRate = value;
					this.SendPropertyChanged("TaxRate");
					this.OnTaxRateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Requisition", DbType="VarChar(8)")]
		public string Requisition
		{
			get
			{
				return this._Requisition;
			}
			set
			{
				if ((this._Requisition != value))
				{
					this.OnRequisitionChanging(value);
					this.SendPropertyChanging();
					this._Requisition = value;
					this.SendPropertyChanged("Requisition");
					this.OnRequisitionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Company", DbType="VarChar(3)")]
		public string Company
		{
			get
			{
				return this._Company;
			}
			set
			{
				if ((this._Company != value))
				{
					this.OnCompanyChanging(value);
					this.SendPropertyChanging();
					this._Company = value;
					this.SendPropertyChanged("Company");
					this.OnCompanyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Division", DbType="VarChar(3)")]
		public string Division
		{
			get
			{
				return this._Division;
			}
			set
			{
				if ((this._Division != value))
				{
					this.OnDivisionChanging(value);
					this.SendPropertyChanging();
					this._Division = value;
					this.SendPropertyChanged("Division");
					this.OnDivisionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POStatus", DbType="Char(1)")]
		public string POStatus
		{
			get
			{
				return this._POStatus;
			}
			set
			{
				if ((this._POStatus != value))
				{
					this.OnPOStatusChanging(value);
					this.SendPropertyChanging();
					this._POStatus = value;
					this.SendPropertyChanged("POStatus");
					this.OnPOStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PODesc", DbType="VarChar(50)")]
		public string PODesc
		{
			get
			{
				return this._PODesc;
			}
			set
			{
				if ((this._PODesc != value))
				{
					this.OnPODescChanging(value);
					this.SendPropertyChanging();
					this._PODesc = value;
					this.SendPropertyChanged("PODesc");
					this.OnPODescChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactID", DbType="VarChar(15)")]
		public string ContactID
		{
			get
			{
				return this._ContactID;
			}
			set
			{
				if ((this._ContactID != value))
				{
					this.OnContactIDChanging(value);
					this.SendPropertyChanging();
					this._ContactID = value;
					this.SendPropertyChanged("ContactID");
					this.OnContactIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PO_POLine", Storage="_POLines", ThisKey="Po1", OtherKey="Po")]
		public EntitySet<POLine> POLines
		{
			get
			{
				return this._POLines;
			}
			set
			{
				this._POLines.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_POLines(POLine entity)
		{
			this.SendPropertyChanging();
			entity.PO1 = this;
		}
		
		private void detach_POLines(POLine entity)
		{
			this.SendPropertyChanging();
			entity.PO1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.POLine")]
	public partial class POLine : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Po;
		
		private int _PoLine1;
		
		private string _Mfg;
		
		private string _Item;
		
		private string _MfgDesc;
		
		private System.Nullable<double> _QtyOrd;
		
		private string _UM;
		
		private System.Nullable<decimal> _Price;
		
		private System.Nullable<decimal> _Ext;
		
		private string _CostCode;
		
		private string _Taxable;
		
		private string _Override;
		
		private System.Nullable<int> _ExpBatch;
		
		private string _ExpSent;
		
		private string _ExtDesc;
		
		private bool _Contract;
		
		private System.Nullable<double> _Division;
		
		private System.Nullable<double> _CostCtr;
		
		private string _Category;
		
		private System.Nullable<double> _QtyIvc;
		
		private EntityRef<PO> _PO1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPoChanging(string value);
    partial void OnPoChanged();
    partial void OnPoLine1Changing(int value);
    partial void OnPoLine1Changed();
    partial void OnMfgChanging(string value);
    partial void OnMfgChanged();
    partial void OnItemChanging(string value);
    partial void OnItemChanged();
    partial void OnMfgDescChanging(string value);
    partial void OnMfgDescChanged();
    partial void OnQtyOrdChanging(System.Nullable<double> value);
    partial void OnQtyOrdChanged();
    partial void OnUMChanging(string value);
    partial void OnUMChanged();
    partial void OnPriceChanging(System.Nullable<decimal> value);
    partial void OnPriceChanged();
    partial void OnExtChanging(System.Nullable<decimal> value);
    partial void OnExtChanged();
    partial void OnCostCodeChanging(string value);
    partial void OnCostCodeChanged();
    partial void OnTaxableChanging(string value);
    partial void OnTaxableChanged();
    partial void OnOverrideChanging(string value);
    partial void OnOverrideChanged();
    partial void OnExpBatchChanging(System.Nullable<int> value);
    partial void OnExpBatchChanged();
    partial void OnExpSentChanging(string value);
    partial void OnExpSentChanged();
    partial void OnExtDescChanging(string value);
    partial void OnExtDescChanged();
    partial void OnContractChanging(bool value);
    partial void OnContractChanged();
    partial void OnDivisionChanging(System.Nullable<double> value);
    partial void OnDivisionChanged();
    partial void OnCostCtrChanging(System.Nullable<double> value);
    partial void OnCostCtrChanged();
    partial void OnCategoryChanging(string value);
    partial void OnCategoryChanged();
    partial void OnQtyIvcChanging(System.Nullable<double> value);
    partial void OnQtyIvcChanged();
    #endregion
		
		public POLine()
		{
			this._PO1 = default(EntityRef<PO>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Po", DbType="VarChar(12) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Po
		{
			get
			{
				return this._Po;
			}
			set
			{
				if ((this._Po != value))
				{
					if (this._PO1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPoChanging(value);
					this.SendPropertyChanging();
					this._Po = value;
					this.SendPropertyChanged("Po");
					this.OnPoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="PoLine", Storage="_PoLine1", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int PoLine1
		{
			get
			{
				return this._PoLine1;
			}
			set
			{
				if ((this._PoLine1 != value))
				{
					this.OnPoLine1Changing(value);
					this.SendPropertyChanging();
					this._PoLine1 = value;
					this.SendPropertyChanged("PoLine1");
					this.OnPoLine1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mfg", DbType="VarChar(6)")]
		public string Mfg
		{
			get
			{
				return this._Mfg;
			}
			set
			{
				if ((this._Mfg != value))
				{
					this.OnMfgChanging(value);
					this.SendPropertyChanging();
					this._Mfg = value;
					this.SendPropertyChanged("Mfg");
					this.OnMfgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Item", DbType="VarChar(5)")]
		public string Item
		{
			get
			{
				return this._Item;
			}
			set
			{
				if ((this._Item != value))
				{
					this.OnItemChanging(value);
					this.SendPropertyChanging();
					this._Item = value;
					this.SendPropertyChanged("Item");
					this.OnItemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MfgDesc", DbType="VarChar(35)")]
		public string MfgDesc
		{
			get
			{
				return this._MfgDesc;
			}
			set
			{
				if ((this._MfgDesc != value))
				{
					this.OnMfgDescChanging(value);
					this.SendPropertyChanging();
					this._MfgDesc = value;
					this.SendPropertyChanged("MfgDesc");
					this.OnMfgDescChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QtyOrd", DbType="Float")]
		public System.Nullable<double> QtyOrd
		{
			get
			{
				return this._QtyOrd;
			}
			set
			{
				if ((this._QtyOrd != value))
				{
					this.OnQtyOrdChanging(value);
					this.SendPropertyChanging();
					this._QtyOrd = value;
					this.SendPropertyChanged("QtyOrd");
					this.OnQtyOrdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UM", DbType="VarChar(2)")]
		public string UM
		{
			get
			{
				return this._UM;
			}
			set
			{
				if ((this._UM != value))
				{
					this.OnUMChanging(value);
					this.SendPropertyChanging();
					this._UM = value;
					this.SendPropertyChanged("UM");
					this.OnUMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="Money")]
		public System.Nullable<decimal> Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this.OnPriceChanging(value);
					this.SendPropertyChanging();
					this._Price = value;
					this.SendPropertyChanged("Price");
					this.OnPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ext", DbType="Money")]
		public System.Nullable<decimal> Ext
		{
			get
			{
				return this._Ext;
			}
			set
			{
				if ((this._Ext != value))
				{
					this.OnExtChanging(value);
					this.SendPropertyChanging();
					this._Ext = value;
					this.SendPropertyChanged("Ext");
					this.OnExtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CostCode", DbType="VarChar(9)")]
		public string CostCode
		{
			get
			{
				return this._CostCode;
			}
			set
			{
				if ((this._CostCode != value))
				{
					this.OnCostCodeChanging(value);
					this.SendPropertyChanging();
					this._CostCode = value;
					this.SendPropertyChanged("CostCode");
					this.OnCostCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Taxable", DbType="VarChar(1)")]
		public string Taxable
		{
			get
			{
				return this._Taxable;
			}
			set
			{
				if ((this._Taxable != value))
				{
					this.OnTaxableChanging(value);
					this.SendPropertyChanging();
					this._Taxable = value;
					this.SendPropertyChanged("Taxable");
					this.OnTaxableChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Override", DbType="VarChar(1)")]
		public string Override
		{
			get
			{
				return this._Override;
			}
			set
			{
				if ((this._Override != value))
				{
					this.OnOverrideChanging(value);
					this.SendPropertyChanging();
					this._Override = value;
					this.SendPropertyChanged("Override");
					this.OnOverrideChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExpBatch", DbType="Int")]
		public System.Nullable<int> ExpBatch
		{
			get
			{
				return this._ExpBatch;
			}
			set
			{
				if ((this._ExpBatch != value))
				{
					this.OnExpBatchChanging(value);
					this.SendPropertyChanging();
					this._ExpBatch = value;
					this.SendPropertyChanged("ExpBatch");
					this.OnExpBatchChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExpSent", DbType="VarChar(1)")]
		public string ExpSent
		{
			get
			{
				return this._ExpSent;
			}
			set
			{
				if ((this._ExpSent != value))
				{
					this.OnExpSentChanging(value);
					this.SendPropertyChanging();
					this._ExpSent = value;
					this.SendPropertyChanged("ExpSent");
					this.OnExpSentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExtDesc", DbType="VarChar(75)")]
		public string ExtDesc
		{
			get
			{
				return this._ExtDesc;
			}
			set
			{
				if ((this._ExtDesc != value))
				{
					this.OnExtDescChanging(value);
					this.SendPropertyChanging();
					this._ExtDesc = value;
					this.SendPropertyChanged("ExtDesc");
					this.OnExtDescChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contract", DbType="Bit NOT NULL")]
		public bool Contract
		{
			get
			{
				return this._Contract;
			}
			set
			{
				if ((this._Contract != value))
				{
					this.OnContractChanging(value);
					this.SendPropertyChanging();
					this._Contract = value;
					this.SendPropertyChanged("Contract");
					this.OnContractChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Division", DbType="Float")]
		public System.Nullable<double> Division
		{
			get
			{
				return this._Division;
			}
			set
			{
				if ((this._Division != value))
				{
					this.OnDivisionChanging(value);
					this.SendPropertyChanging();
					this._Division = value;
					this.SendPropertyChanged("Division");
					this.OnDivisionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CostCtr", DbType="Float")]
		public System.Nullable<double> CostCtr
		{
			get
			{
				return this._CostCtr;
			}
			set
			{
				if ((this._CostCtr != value))
				{
					this.OnCostCtrChanging(value);
					this.SendPropertyChanging();
					this._CostCtr = value;
					this.SendPropertyChanged("CostCtr");
					this.OnCostCtrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Category", DbType="VarChar(2)")]
		public string Category
		{
			get
			{
				return this._Category;
			}
			set
			{
				if ((this._Category != value))
				{
					this.OnCategoryChanging(value);
					this.SendPropertyChanging();
					this._Category = value;
					this.SendPropertyChanged("Category");
					this.OnCategoryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QtyIvc", DbType="Float")]
		public System.Nullable<double> QtyIvc
		{
			get
			{
				return this._QtyIvc;
			}
			set
			{
				if ((this._QtyIvc != value))
				{
					this.OnQtyIvcChanging(value);
					this.SendPropertyChanging();
					this._QtyIvc = value;
					this.SendPropertyChanged("QtyIvc");
					this.OnQtyIvcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PO_POLine", Storage="_PO1", ThisKey="Po", OtherKey="Po1", IsForeignKey=true)]
		public PO PO1
		{
			get
			{
				return this._PO1.Entity;
			}
			set
			{
				PO previousValue = this._PO1.Entity;
				if (((previousValue != value) 
							|| (this._PO1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PO1.Entity = null;
						previousValue.POLines.Remove(this);
					}
					this._PO1.Entity = value;
					if ((value != null))
					{
						value.POLines.Add(this);
						this._Po = value.Po1;
					}
					else
					{
						this._Po = default(string);
					}
					this.SendPropertyChanged("PO1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.COINSESB_WBS")]
	public partial class COINSESB_WB : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Job;
		
		private string _WB_Code;
		
		private string _WB_Desc;
		
		private string _Activity;
		
		private string _Section;
		
		private System.Nullable<bool> _UsesActivity;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnJobChanging(string value);
    partial void OnJobChanged();
    partial void OnWB_CodeChanging(string value);
    partial void OnWB_CodeChanged();
    partial void OnWB_DescChanging(string value);
    partial void OnWB_DescChanged();
    partial void OnActivityChanging(string value);
    partial void OnActivityChanged();
    partial void OnSectionChanging(string value);
    partial void OnSectionChanged();
    partial void OnUsesActivityChanging(System.Nullable<bool> value);
    partial void OnUsesActivityChanged();
    #endregion
		
		public COINSESB_WB()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Job", DbType="VarChar(12) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Job
		{
			get
			{
				return this._Job;
			}
			set
			{
				if ((this._Job != value))
				{
					this.OnJobChanging(value);
					this.SendPropertyChanging();
					this._Job = value;
					this.SendPropertyChanged("Job");
					this.OnJobChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WB_Code", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string WB_Code
		{
			get
			{
				return this._WB_Code;
			}
			set
			{
				if ((this._WB_Code != value))
				{
					this.OnWB_CodeChanging(value);
					this.SendPropertyChanging();
					this._WB_Code = value;
					this.SendPropertyChanged("WB_Code");
					this.OnWB_CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WB_Desc", DbType="VarChar(50)")]
		public string WB_Desc
		{
			get
			{
				return this._WB_Desc;
			}
			set
			{
				if ((this._WB_Desc != value))
				{
					this.OnWB_DescChanging(value);
					this.SendPropertyChanging();
					this._WB_Desc = value;
					this.SendPropertyChanged("WB_Desc");
					this.OnWB_DescChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Activity", DbType="VarChar(50)")]
		public string Activity
		{
			get
			{
				return this._Activity;
			}
			set
			{
				if ((this._Activity != value))
				{
					this.OnActivityChanging(value);
					this.SendPropertyChanging();
					this._Activity = value;
					this.SendPropertyChanged("Activity");
					this.OnActivityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Section", DbType="VarChar(50)")]
		public string Section
		{
			get
			{
				return this._Section;
			}
			set
			{
				if ((this._Section != value))
				{
					this.OnSectionChanging(value);
					this.SendPropertyChanging();
					this._Section = value;
					this.SendPropertyChanged("Section");
					this.OnSectionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsesActivity", DbType="Bit")]
		public System.Nullable<bool> UsesActivity
		{
			get
			{
				return this._UsesActivity;
			}
			set
			{
				if ((this._UsesActivity != value))
				{
					this.OnUsesActivityChanging(value);
					this.SendPropertyChanging();
					this._UsesActivity = value;
					this.SendPropertyChanged("UsesActivity");
					this.OnUsesActivityChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Contact")]
	public partial class Contact : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ContactID;
		
		private string _ContactName;
		
		private string _ContactPosition;
		
		private string _ContactAdd1;
		
		private string _ContactAdd2;
		
		private string _ContactCity;
		
		private string _ContactState;
		
		private string _ContactZip;
		
		private string _ContactEmail;
		
		private string _ContactPhone;
		
		private string _ContactPassword;
		
		private System.Nullable<char> _ViewPricing;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnContactIDChanging(string value);
    partial void OnContactIDChanged();
    partial void OnContactNameChanging(string value);
    partial void OnContactNameChanged();
    partial void OnContactPositionChanging(string value);
    partial void OnContactPositionChanged();
    partial void OnContactAdd1Changing(string value);
    partial void OnContactAdd1Changed();
    partial void OnContactAdd2Changing(string value);
    partial void OnContactAdd2Changed();
    partial void OnContactCityChanging(string value);
    partial void OnContactCityChanged();
    partial void OnContactStateChanging(string value);
    partial void OnContactStateChanged();
    partial void OnContactZipChanging(string value);
    partial void OnContactZipChanged();
    partial void OnContactEmailChanging(string value);
    partial void OnContactEmailChanged();
    partial void OnContactPhoneChanging(string value);
    partial void OnContactPhoneChanged();
    partial void OnContactPasswordChanging(string value);
    partial void OnContactPasswordChanged();
    partial void OnViewPricingChanging(System.Nullable<char> value);
    partial void OnViewPricingChanged();
    #endregion
		
		public Contact()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactID", DbType="VarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ContactID
		{
			get
			{
				return this._ContactID;
			}
			set
			{
				if ((this._ContactID != value))
				{
					this.OnContactIDChanging(value);
					this.SendPropertyChanging();
					this._ContactID = value;
					this.SendPropertyChanged("ContactID");
					this.OnContactIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactName", DbType="VarChar(35) NOT NULL", CanBeNull=false)]
		public string ContactName
		{
			get
			{
				return this._ContactName;
			}
			set
			{
				if ((this._ContactName != value))
				{
					this.OnContactNameChanging(value);
					this.SendPropertyChanging();
					this._ContactName = value;
					this.SendPropertyChanged("ContactName");
					this.OnContactNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactPosition", DbType="VarChar(35)")]
		public string ContactPosition
		{
			get
			{
				return this._ContactPosition;
			}
			set
			{
				if ((this._ContactPosition != value))
				{
					this.OnContactPositionChanging(value);
					this.SendPropertyChanging();
					this._ContactPosition = value;
					this.SendPropertyChanged("ContactPosition");
					this.OnContactPositionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactAdd1", DbType="VarChar(25)")]
		public string ContactAdd1
		{
			get
			{
				return this._ContactAdd1;
			}
			set
			{
				if ((this._ContactAdd1 != value))
				{
					this.OnContactAdd1Changing(value);
					this.SendPropertyChanging();
					this._ContactAdd1 = value;
					this.SendPropertyChanged("ContactAdd1");
					this.OnContactAdd1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactAdd2", DbType="VarChar(25)")]
		public string ContactAdd2
		{
			get
			{
				return this._ContactAdd2;
			}
			set
			{
				if ((this._ContactAdd2 != value))
				{
					this.OnContactAdd2Changing(value);
					this.SendPropertyChanging();
					this._ContactAdd2 = value;
					this.SendPropertyChanged("ContactAdd2");
					this.OnContactAdd2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactCity", DbType="VarChar(15)")]
		public string ContactCity
		{
			get
			{
				return this._ContactCity;
			}
			set
			{
				if ((this._ContactCity != value))
				{
					this.OnContactCityChanging(value);
					this.SendPropertyChanging();
					this._ContactCity = value;
					this.SendPropertyChanged("ContactCity");
					this.OnContactCityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactState", DbType="VarChar(4)")]
		public string ContactState
		{
			get
			{
				return this._ContactState;
			}
			set
			{
				if ((this._ContactState != value))
				{
					this.OnContactStateChanging(value);
					this.SendPropertyChanging();
					this._ContactState = value;
					this.SendPropertyChanged("ContactState");
					this.OnContactStateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactZip", DbType="VarChar(15)")]
		public string ContactZip
		{
			get
			{
				return this._ContactZip;
			}
			set
			{
				if ((this._ContactZip != value))
				{
					this.OnContactZipChanging(value);
					this.SendPropertyChanging();
					this._ContactZip = value;
					this.SendPropertyChanged("ContactZip");
					this.OnContactZipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactEmail", DbType="VarChar(64)")]
		public string ContactEmail
		{
			get
			{
				return this._ContactEmail;
			}
			set
			{
				if ((this._ContactEmail != value))
				{
					this.OnContactEmailChanging(value);
					this.SendPropertyChanging();
					this._ContactEmail = value;
					this.SendPropertyChanged("ContactEmail");
					this.OnContactEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactPhone", DbType="VarChar(15)")]
		public string ContactPhone
		{
			get
			{
				return this._ContactPhone;
			}
			set
			{
				if ((this._ContactPhone != value))
				{
					this.OnContactPhoneChanging(value);
					this.SendPropertyChanging();
					this._ContactPhone = value;
					this.SendPropertyChanged("ContactPhone");
					this.OnContactPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactPassword", DbType="VarChar(16)")]
		public string ContactPassword
		{
			get
			{
				return this._ContactPassword;
			}
			set
			{
				if ((this._ContactPassword != value))
				{
					this.OnContactPasswordChanging(value);
					this.SendPropertyChanging();
					this._ContactPassword = value;
					this.SendPropertyChanged("ContactPassword");
					this.OnContactPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ViewPricing", DbType="Char(1)")]
		public System.Nullable<char> ViewPricing
		{
			get
			{
				return this._ViewPricing;
			}
			set
			{
				if ((this._ViewPricing != value))
				{
					this.OnViewPricingChanging(value);
					this.SendPropertyChanging();
					this._ViewPricing = value;
					this.SendPropertyChanged("ViewPricing");
					this.OnViewPricingChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.System")]
	public partial class ApexSystem : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Name;
		
		private string _Add1;
		
		private string _Add2;
		
		private string _City;
		
		private string _State;
		
		private string _Zip;
		
		private string _Attn;
		
		private string _Phone;
		
		private string _Fax;
		
		private string _EMail;
		
		private System.Nullable<int> _Rev;
		
		private System.Nullable<int> _Serial;
		
		private string _Company;
		
		private string _CompanyType;
		
		private System.Nullable<int> _ExportBatch;
		
		private System.Nullable<int> _NextPO;
		
		private System.Nullable<int> _Version;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnAdd1Changing(string value);
    partial void OnAdd1Changed();
    partial void OnAdd2Changing(string value);
    partial void OnAdd2Changed();
    partial void OnCityChanging(string value);
    partial void OnCityChanged();
    partial void OnStateChanging(string value);
    partial void OnStateChanged();
    partial void OnZipChanging(string value);
    partial void OnZipChanged();
    partial void OnAttnChanging(string value);
    partial void OnAttnChanged();
    partial void OnPhoneChanging(string value);
    partial void OnPhoneChanged();
    partial void OnFaxChanging(string value);
    partial void OnFaxChanged();
    partial void OnEMailChanging(string value);
    partial void OnEMailChanged();
    partial void OnRevChanging(System.Nullable<int> value);
    partial void OnRevChanged();
    partial void OnSerialChanging(System.Nullable<int> value);
    partial void OnSerialChanged();
    partial void OnCompanyChanging(string value);
    partial void OnCompanyChanged();
    partial void OnCompanyTypeChanging(string value);
    partial void OnCompanyTypeChanged();
    partial void OnExportBatchChanging(System.Nullable<int> value);
    partial void OnExportBatchChanged();
    partial void OnNextPOChanging(System.Nullable<int> value);
    partial void OnNextPOChanged();
    partial void OnVersionChanging(System.Nullable<int> value);
    partial void OnVersionChanged();
    #endregion
		
		public ApexSystem()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(25)", IsPrimaryKey=true)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Add1", DbType="VarChar(25)")]
		public string Add1
		{
			get
			{
				return this._Add1;
			}
			set
			{
				if ((this._Add1 != value))
				{
					this.OnAdd1Changing(value);
					this.SendPropertyChanging();
					this._Add1 = value;
					this.SendPropertyChanged("Add1");
					this.OnAdd1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Add2", DbType="VarChar(25)")]
		public string Add2
		{
			get
			{
				return this._Add2;
			}
			set
			{
				if ((this._Add2 != value))
				{
					this.OnAdd2Changing(value);
					this.SendPropertyChanging();
					this._Add2 = value;
					this.SendPropertyChanged("Add2");
					this.OnAdd2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="VarChar(15)")]
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				if ((this._City != value))
				{
					this.OnCityChanging(value);
					this.SendPropertyChanging();
					this._City = value;
					this.SendPropertyChanged("City");
					this.OnCityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State", DbType="VarChar(4)")]
		public string State
		{
			get
			{
				return this._State;
			}
			set
			{
				if ((this._State != value))
				{
					this.OnStateChanging(value);
					this.SendPropertyChanging();
					this._State = value;
					this.SendPropertyChanged("State");
					this.OnStateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zip", DbType="VarChar(15)")]
		public string Zip
		{
			get
			{
				return this._Zip;
			}
			set
			{
				if ((this._Zip != value))
				{
					this.OnZipChanging(value);
					this.SendPropertyChanging();
					this._Zip = value;
					this.SendPropertyChanged("Zip");
					this.OnZipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Attn", DbType="VarChar(20)")]
		public string Attn
		{
			get
			{
				return this._Attn;
			}
			set
			{
				if ((this._Attn != value))
				{
					this.OnAttnChanging(value);
					this.SendPropertyChanging();
					this._Attn = value;
					this.SendPropertyChanged("Attn");
					this.OnAttnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="VarChar(15)")]
		public string Phone
		{
			get
			{
				return this._Phone;
			}
			set
			{
				if ((this._Phone != value))
				{
					this.OnPhoneChanging(value);
					this.SendPropertyChanging();
					this._Phone = value;
					this.SendPropertyChanged("Phone");
					this.OnPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fax", DbType="VarChar(15)")]
		public string Fax
		{
			get
			{
				return this._Fax;
			}
			set
			{
				if ((this._Fax != value))
				{
					this.OnFaxChanging(value);
					this.SendPropertyChanging();
					this._Fax = value;
					this.SendPropertyChanged("Fax");
					this.OnFaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMail", DbType="VarChar(40)")]
		public string EMail
		{
			get
			{
				return this._EMail;
			}
			set
			{
				if ((this._EMail != value))
				{
					this.OnEMailChanging(value);
					this.SendPropertyChanging();
					this._EMail = value;
					this.SendPropertyChanged("EMail");
					this.OnEMailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rev", DbType="Int")]
		public System.Nullable<int> Rev
		{
			get
			{
				return this._Rev;
			}
			set
			{
				if ((this._Rev != value))
				{
					this.OnRevChanging(value);
					this.SendPropertyChanging();
					this._Rev = value;
					this.SendPropertyChanged("Rev");
					this.OnRevChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Serial", DbType="Int")]
		public System.Nullable<int> Serial
		{
			get
			{
				return this._Serial;
			}
			set
			{
				if ((this._Serial != value))
				{
					this.OnSerialChanging(value);
					this.SendPropertyChanging();
					this._Serial = value;
					this.SendPropertyChanged("Serial");
					this.OnSerialChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Company", DbType="VarChar(25)")]
		public string Company
		{
			get
			{
				return this._Company;
			}
			set
			{
				if ((this._Company != value))
				{
					this.OnCompanyChanging(value);
					this.SendPropertyChanging();
					this._Company = value;
					this.SendPropertyChanged("Company");
					this.OnCompanyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyType", DbType="VarChar(1)")]
		public string CompanyType
		{
			get
			{
				return this._CompanyType;
			}
			set
			{
				if ((this._CompanyType != value))
				{
					this.OnCompanyTypeChanging(value);
					this.SendPropertyChanging();
					this._CompanyType = value;
					this.SendPropertyChanged("CompanyType");
					this.OnCompanyTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExportBatch", DbType="Int")]
		public System.Nullable<int> ExportBatch
		{
			get
			{
				return this._ExportBatch;
			}
			set
			{
				if ((this._ExportBatch != value))
				{
					this.OnExportBatchChanging(value);
					this.SendPropertyChanging();
					this._ExportBatch = value;
					this.SendPropertyChanged("ExportBatch");
					this.OnExportBatchChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NextPO", DbType="Int")]
		public System.Nullable<int> NextPO
		{
			get
			{
				return this._NextPO;
			}
			set
			{
				if ((this._NextPO != value))
				{
					this.OnNextPOChanging(value);
					this.SendPropertyChanging();
					this._NextPO = value;
					this.SendPropertyChanged("NextPO");
					this.OnNextPOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Version", DbType="Int")]
		public System.Nullable<int> Version
		{
			get
			{
				return this._Version;
			}
			set
			{
				if ((this._Version != value))
				{
					this.OnVersionChanging(value);
					this.SendPropertyChanging();
					this._Version = value;
					this.SendPropertyChanged("Version");
					this.OnVersionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Job")]
	public partial class Job : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Job1;
		
		private string _Name;
		
		private string _Schedule;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnJob1Changing(string value);
    partial void OnJob1Changed();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnScheduleChanging(string value);
    partial void OnScheduleChanged();
    #endregion
		
		public Job()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Job", Storage="_Job1", DbType="VarChar(12) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Job1
		{
			get
			{
				return this._Job1;
			}
			set
			{
				if ((this._Job1 != value))
				{
					this.OnJob1Changing(value);
					this.SendPropertyChanging();
					this._Job1 = value;
					this.SendPropertyChanged("Job1");
					this.OnJob1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(25)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Schedule", DbType="VarChar(5)")]
		public string Schedule
		{
			get
			{
				return this._Schedule;
			}
			set
			{
				if ((this._Schedule != value))
				{
					this.OnScheduleChanging(value);
					this.SendPropertyChanging();
					this._Schedule = value;
					this.SendPropertyChanged("Schedule");
					this.OnScheduleChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Costcode")]
	public partial class Costcode : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Schedule;
		
		private string _CostCode1;
		
		private string _Description;
		
		private string _GL;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnScheduleChanging(string value);
    partial void OnScheduleChanged();
    partial void OnCostCode1Changing(string value);
    partial void OnCostCode1Changed();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnGLChanging(string value);
    partial void OnGLChanged();
    #endregion
		
		public Costcode()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Schedule", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Schedule
		{
			get
			{
				return this._Schedule;
			}
			set
			{
				if ((this._Schedule != value))
				{
					this.OnScheduleChanging(value);
					this.SendPropertyChanging();
					this._Schedule = value;
					this.SendPropertyChanged("Schedule");
					this.OnScheduleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="CostCode", Storage="_CostCode1", DbType="VarChar(9) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CostCode1
		{
			get
			{
				return this._CostCode1;
			}
			set
			{
				if ((this._CostCode1 != value))
				{
					this.OnCostCode1Changing(value);
					this.SendPropertyChanging();
					this._CostCode1 = value;
					this.SendPropertyChanged("CostCode1");
					this.OnCostCode1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(35)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GL", DbType="VarChar(6)")]
		public string GL
		{
			get
			{
				return this._GL;
			}
			set
			{
				if ((this._GL != value))
				{
					this.OnGLChanging(value);
					this.SendPropertyChanging();
					this._GL = value;
					this.SendPropertyChanged("GL");
					this.OnGLChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.COINSESB_ExpL")]
	public partial class COINSESB_ExpL : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _PO;
		
		private int _POLine;
		
		private System.Nullable<decimal> _LastAmt;
		
		private System.Nullable<int> _POL_Seq;
		
		private System.Nullable<decimal> _LastPrice;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPOChanging(string value);
    partial void OnPOChanged();
    partial void OnPOLineChanging(int value);
    partial void OnPOLineChanged();
    partial void OnLastAmtChanging(System.Nullable<decimal> value);
    partial void OnLastAmtChanged();
    partial void OnPOL_SeqChanging(System.Nullable<int> value);
    partial void OnPOL_SeqChanged();
    partial void OnLastPriceChanging(System.Nullable<decimal> value);
    partial void OnLastPriceChanged();
    #endregion
		
		public COINSESB_ExpL()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PO", DbType="VarChar(12) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string PO
		{
			get
			{
				return this._PO;
			}
			set
			{
				if ((this._PO != value))
				{
					this.OnPOChanging(value);
					this.SendPropertyChanging();
					this._PO = value;
					this.SendPropertyChanged("PO");
					this.OnPOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POLine", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int POLine
		{
			get
			{
				return this._POLine;
			}
			set
			{
				if ((this._POLine != value))
				{
					this.OnPOLineChanging(value);
					this.SendPropertyChanging();
					this._POLine = value;
					this.SendPropertyChanged("POLine");
					this.OnPOLineChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastAmt", DbType="Money")]
		public System.Nullable<decimal> LastAmt
		{
			get
			{
				return this._LastAmt;
			}
			set
			{
				if ((this._LastAmt != value))
				{
					this.OnLastAmtChanging(value);
					this.SendPropertyChanging();
					this._LastAmt = value;
					this.SendPropertyChanged("LastAmt");
					this.OnLastAmtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POL_Seq", DbType="Int")]
		public System.Nullable<int> POL_Seq
		{
			get
			{
				return this._POL_Seq;
			}
			set
			{
				if ((this._POL_Seq != value))
				{
					this.OnPOL_SeqChanging(value);
					this.SendPropertyChanging();
					this._POL_Seq = value;
					this.SendPropertyChanged("POL_Seq");
					this.OnPOL_SeqChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastPrice", DbType="Money")]
		public System.Nullable<decimal> LastPrice
		{
			get
			{
				return this._LastPrice;
			}
			set
			{
				if ((this._LastPrice != value))
				{
					this.OnLastPriceChanging(value);
					this.SendPropertyChanging();
					this._LastPrice = value;
					this.SendPropertyChanged("LastPrice");
					this.OnLastPriceChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
