#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COINSImport
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ApexVEC")]
	public partial class ApexDataDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertVendor(Vendor instance);
    partial void UpdateVendor(Vendor instance);
    partial void DeleteVendor(Vendor instance);
    partial void InsertJob(Job instance);
    partial void UpdateJob(Job instance);
    partial void DeleteJob(Job instance);
    partial void InsertJobPhase(JobPhase instance);
    partial void UpdateJobPhase(JobPhase instance);
    partial void DeleteJobPhase(JobPhase instance);
    partial void InsertJobPhCcd(JobPhCcd instance);
    partial void UpdateJobPhCcd(JobPhCcd instance);
    partial void DeleteJobPhCcd(JobPhCcd instance);
    partial void InsertCOINSESB_WB(COINSESB_WB instance);
    partial void UpdateCOINSESB_WB(COINSESB_WB instance);
    partial void DeleteCOINSESB_WB(COINSESB_WB instance);
    partial void InsertWO(WO instance);
    partial void UpdateWO(WO instance);
    partial void DeleteWO(WO instance);
    #endregion
		
		public ApexDataDataContext() : 
				base(global::COINSImport.Properties.Settings.Default.ApexConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ApexDataDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ApexDataDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ApexDataDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ApexDataDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Vendor> Vendors
		{
			get
			{
				return this.GetTable<Vendor>();
			}
		}
		
		public System.Data.Linq.Table<Job> Jobs
		{
			get
			{
				return this.GetTable<Job>();
			}
		}
		
		public System.Data.Linq.Table<JobPhase> JobPhases
		{
			get
			{
				return this.GetTable<JobPhase>();
			}
		}
		
		public System.Data.Linq.Table<JobPhCcd> JobPhCcds
		{
			get
			{
				return this.GetTable<JobPhCcd>();
			}
		}
		
		public System.Data.Linq.Table<COINSESB_WB> COINSESB_WBs
		{
			get
			{
				return this.GetTable<COINSESB_WB>();
			}
		}
		
		public System.Data.Linq.Table<WO> WOs
		{
			get
			{
				return this.GetTable<WO>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Vendor")]
	public partial class Vendor : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Vendor1;
		
		private string _Name;
		
		private string _Add1;
		
		private string _Add2;
		
		private string _City;
		
		private string _State;
		
		private string _Zip;
		
		private string _Attn;
		
		private string _Phone;
		
		private string _Fax;
		
		private string _EMail;
		
		private string _Terms;
		
		private System.Nullable<int> _CompLevel;
		
		private string _PermitLow;
		
		private System.Nullable<double> _TaxRate;
		
		private string _Abbrev;
		
		private string _POMsg;
		
		private string _AcctID;
		
		private string _Company;
		
		private string _PurchasingMsg;
		
		private string _OnlineStatus;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnVendor1Changing(string value);
    partial void OnVendor1Changed();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnAdd1Changing(string value);
    partial void OnAdd1Changed();
    partial void OnAdd2Changing(string value);
    partial void OnAdd2Changed();
    partial void OnCityChanging(string value);
    partial void OnCityChanged();
    partial void OnStateChanging(string value);
    partial void OnStateChanged();
    partial void OnZipChanging(string value);
    partial void OnZipChanged();
    partial void OnAttnChanging(string value);
    partial void OnAttnChanged();
    partial void OnPhoneChanging(string value);
    partial void OnPhoneChanged();
    partial void OnFaxChanging(string value);
    partial void OnFaxChanged();
    partial void OnEMailChanging(string value);
    partial void OnEMailChanged();
    partial void OnTermsChanging(string value);
    partial void OnTermsChanged();
    partial void OnCompLevelChanging(System.Nullable<int> value);
    partial void OnCompLevelChanged();
    partial void OnPermitLowChanging(string value);
    partial void OnPermitLowChanged();
    partial void OnTaxRateChanging(System.Nullable<double> value);
    partial void OnTaxRateChanged();
    partial void OnAbbrevChanging(string value);
    partial void OnAbbrevChanged();
    partial void OnPOMsgChanging(string value);
    partial void OnPOMsgChanged();
    partial void OnAcctIDChanging(string value);
    partial void OnAcctIDChanged();
    partial void OnCompanyChanging(string value);
    partial void OnCompanyChanged();
    partial void OnPurchasingMsgChanging(string value);
    partial void OnPurchasingMsgChanged();
    partial void OnOnlineStatusChanging(string value);
    partial void OnOnlineStatusChanged();
    #endregion
		
		public Vendor()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Vendor", Storage="_Vendor1", DbType="VarChar(6) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Vendor1
		{
			get
			{
				return this._Vendor1;
			}
			set
			{
				if ((this._Vendor1 != value))
				{
					this.OnVendor1Changing(value);
					this.SendPropertyChanging();
					this._Vendor1 = value;
					this.SendPropertyChanged("Vendor1");
					this.OnVendor1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(25)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Add1", DbType="VarChar(25)")]
		public string Add1
		{
			get
			{
				return this._Add1;
			}
			set
			{
				if ((this._Add1 != value))
				{
					this.OnAdd1Changing(value);
					this.SendPropertyChanging();
					this._Add1 = value;
					this.SendPropertyChanged("Add1");
					this.OnAdd1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Add2", DbType="VarChar(25)")]
		public string Add2
		{
			get
			{
				return this._Add2;
			}
			set
			{
				if ((this._Add2 != value))
				{
					this.OnAdd2Changing(value);
					this.SendPropertyChanging();
					this._Add2 = value;
					this.SendPropertyChanged("Add2");
					this.OnAdd2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="VarChar(15)")]
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				if ((this._City != value))
				{
					this.OnCityChanging(value);
					this.SendPropertyChanging();
					this._City = value;
					this.SendPropertyChanged("City");
					this.OnCityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State", DbType="VarChar(4)")]
		public string State
		{
			get
			{
				return this._State;
			}
			set
			{
				if ((this._State != value))
				{
					this.OnStateChanging(value);
					this.SendPropertyChanging();
					this._State = value;
					this.SendPropertyChanged("State");
					this.OnStateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zip", DbType="VarChar(15)")]
		public string Zip
		{
			get
			{
				return this._Zip;
			}
			set
			{
				if ((this._Zip != value))
				{
					this.OnZipChanging(value);
					this.SendPropertyChanging();
					this._Zip = value;
					this.SendPropertyChanged("Zip");
					this.OnZipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Attn", DbType="VarChar(20)")]
		public string Attn
		{
			get
			{
				return this._Attn;
			}
			set
			{
				if ((this._Attn != value))
				{
					this.OnAttnChanging(value);
					this.SendPropertyChanging();
					this._Attn = value;
					this.SendPropertyChanged("Attn");
					this.OnAttnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="VarChar(15)")]
		public string Phone
		{
			get
			{
				return this._Phone;
			}
			set
			{
				if ((this._Phone != value))
				{
					this.OnPhoneChanging(value);
					this.SendPropertyChanging();
					this._Phone = value;
					this.SendPropertyChanged("Phone");
					this.OnPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fax", DbType="VarChar(15)")]
		public string Fax
		{
			get
			{
				return this._Fax;
			}
			set
			{
				if ((this._Fax != value))
				{
					this.OnFaxChanging(value);
					this.SendPropertyChanging();
					this._Fax = value;
					this.SendPropertyChanged("Fax");
					this.OnFaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMail", DbType="VarChar(40)")]
		public string EMail
		{
			get
			{
				return this._EMail;
			}
			set
			{
				if ((this._EMail != value))
				{
					this.OnEMailChanging(value);
					this.SendPropertyChanging();
					this._EMail = value;
					this.SendPropertyChanged("EMail");
					this.OnEMailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Terms", DbType="VarChar(15)")]
		public string Terms
		{
			get
			{
				return this._Terms;
			}
			set
			{
				if ((this._Terms != value))
				{
					this.OnTermsChanging(value);
					this.SendPropertyChanging();
					this._Terms = value;
					this.SendPropertyChanged("Terms");
					this.OnTermsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompLevel", DbType="Int")]
		public System.Nullable<int> CompLevel
		{
			get
			{
				return this._CompLevel;
			}
			set
			{
				if ((this._CompLevel != value))
				{
					this.OnCompLevelChanging(value);
					this.SendPropertyChanging();
					this._CompLevel = value;
					this.SendPropertyChanged("CompLevel");
					this.OnCompLevelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PermitLow", DbType="VarChar(1)")]
		public string PermitLow
		{
			get
			{
				return this._PermitLow;
			}
			set
			{
				if ((this._PermitLow != value))
				{
					this.OnPermitLowChanging(value);
					this.SendPropertyChanging();
					this._PermitLow = value;
					this.SendPropertyChanged("PermitLow");
					this.OnPermitLowChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaxRate", DbType="Float")]
		public System.Nullable<double> TaxRate
		{
			get
			{
				return this._TaxRate;
			}
			set
			{
				if ((this._TaxRate != value))
				{
					this.OnTaxRateChanging(value);
					this.SendPropertyChanging();
					this._TaxRate = value;
					this.SendPropertyChanged("TaxRate");
					this.OnTaxRateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Abbrev", DbType="VarChar(8)")]
		public string Abbrev
		{
			get
			{
				return this._Abbrev;
			}
			set
			{
				if ((this._Abbrev != value))
				{
					this.OnAbbrevChanging(value);
					this.SendPropertyChanging();
					this._Abbrev = value;
					this.SendPropertyChanged("Abbrev");
					this.OnAbbrevChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POMsg", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string POMsg
		{
			get
			{
				return this._POMsg;
			}
			set
			{
				if ((this._POMsg != value))
				{
					this.OnPOMsgChanging(value);
					this.SendPropertyChanging();
					this._POMsg = value;
					this.SendPropertyChanged("POMsg");
					this.OnPOMsgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AcctID", DbType="VarChar(6)")]
		public string AcctID
		{
			get
			{
				return this._AcctID;
			}
			set
			{
				if ((this._AcctID != value))
				{
					this.OnAcctIDChanging(value);
					this.SendPropertyChanging();
					this._AcctID = value;
					this.SendPropertyChanged("AcctID");
					this.OnAcctIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Company", DbType="VarChar(3)")]
		public string Company
		{
			get
			{
				return this._Company;
			}
			set
			{
				if ((this._Company != value))
				{
					this.OnCompanyChanging(value);
					this.SendPropertyChanging();
					this._Company = value;
					this.SendPropertyChanged("Company");
					this.OnCompanyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PurchasingMsg", DbType="VarChar(2000)")]
		public string PurchasingMsg
		{
			get
			{
				return this._PurchasingMsg;
			}
			set
			{
				if ((this._PurchasingMsg != value))
				{
					this.OnPurchasingMsgChanging(value);
					this.SendPropertyChanging();
					this._PurchasingMsg = value;
					this.SendPropertyChanged("PurchasingMsg");
					this.OnPurchasingMsgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OnlineStatus", DbType="VarChar(1)")]
		public string OnlineStatus
		{
			get
			{
				return this._OnlineStatus;
			}
			set
			{
				if ((this._OnlineStatus != value))
				{
					this.OnOnlineStatusChanging(value);
					this.SendPropertyChanging();
					this._OnlineStatus = value;
					this.SendPropertyChanged("OnlineStatus");
					this.OnOnlineStatusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Job")]
	public partial class Job : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Job1;
		
		private string _Name;
		
		private string _Add1;
		
		private string _Add2;
		
		private string _City;
		
		private string _State;
		
		private string _Zip;
		
		private string _Attn;
		
		private string _Phone;
		
		private string _Fax;
		
		private string _EMail;
		
		private System.Nullable<decimal> _Budget;
		
		private System.Nullable<decimal> _JobTotal;
		
		private string _TaxDefault;
		
		private string _Schedule;
		
		private string _TaxID;
		
		private System.Nullable<double> _TaxRate;
		
		private string _POMsg;
		
		private string _Company;
		
		private string _Division;
		
		private System.Nullable<double> _CostCtr;
		
		private string _Act;
		
		private string _PurchasingMsg;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnJob1Changing(string value);
    partial void OnJob1Changed();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnAdd1Changing(string value);
    partial void OnAdd1Changed();
    partial void OnAdd2Changing(string value);
    partial void OnAdd2Changed();
    partial void OnCityChanging(string value);
    partial void OnCityChanged();
    partial void OnStateChanging(string value);
    partial void OnStateChanged();
    partial void OnZipChanging(string value);
    partial void OnZipChanged();
    partial void OnAttnChanging(string value);
    partial void OnAttnChanged();
    partial void OnPhoneChanging(string value);
    partial void OnPhoneChanged();
    partial void OnFaxChanging(string value);
    partial void OnFaxChanged();
    partial void OnEMailChanging(string value);
    partial void OnEMailChanged();
    partial void OnBudgetChanging(System.Nullable<decimal> value);
    partial void OnBudgetChanged();
    partial void OnJobTotalChanging(System.Nullable<decimal> value);
    partial void OnJobTotalChanged();
    partial void OnTaxDefaultChanging(string value);
    partial void OnTaxDefaultChanged();
    partial void OnScheduleChanging(string value);
    partial void OnScheduleChanged();
    partial void OnTaxIDChanging(string value);
    partial void OnTaxIDChanged();
    partial void OnTaxRateChanging(System.Nullable<double> value);
    partial void OnTaxRateChanged();
    partial void OnPOMsgChanging(string value);
    partial void OnPOMsgChanged();
    partial void OnCompanyChanging(string value);
    partial void OnCompanyChanged();
    partial void OnDivisionChanging(string value);
    partial void OnDivisionChanged();
    partial void OnCostCtrChanging(System.Nullable<double> value);
    partial void OnCostCtrChanged();
    partial void OnActChanging(string value);
    partial void OnActChanged();
    partial void OnPurchasingMsgChanging(string value);
    partial void OnPurchasingMsgChanged();
    #endregion
		
		public Job()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Job", Storage="_Job1", DbType="VarChar(12) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Job1
		{
			get
			{
				return this._Job1;
			}
			set
			{
				if ((this._Job1 != value))
				{
					this.OnJob1Changing(value);
					this.SendPropertyChanging();
					this._Job1 = value;
					this.SendPropertyChanged("Job1");
					this.OnJob1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(25)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Add1", DbType="VarChar(25)")]
		public string Add1
		{
			get
			{
				return this._Add1;
			}
			set
			{
				if ((this._Add1 != value))
				{
					this.OnAdd1Changing(value);
					this.SendPropertyChanging();
					this._Add1 = value;
					this.SendPropertyChanged("Add1");
					this.OnAdd1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Add2", DbType="VarChar(25)")]
		public string Add2
		{
			get
			{
				return this._Add2;
			}
			set
			{
				if ((this._Add2 != value))
				{
					this.OnAdd2Changing(value);
					this.SendPropertyChanging();
					this._Add2 = value;
					this.SendPropertyChanged("Add2");
					this.OnAdd2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="VarChar(15)")]
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				if ((this._City != value))
				{
					this.OnCityChanging(value);
					this.SendPropertyChanging();
					this._City = value;
					this.SendPropertyChanged("City");
					this.OnCityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State", DbType="VarChar(4)")]
		public string State
		{
			get
			{
				return this._State;
			}
			set
			{
				if ((this._State != value))
				{
					this.OnStateChanging(value);
					this.SendPropertyChanging();
					this._State = value;
					this.SendPropertyChanged("State");
					this.OnStateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zip", DbType="VarChar(15)")]
		public string Zip
		{
			get
			{
				return this._Zip;
			}
			set
			{
				if ((this._Zip != value))
				{
					this.OnZipChanging(value);
					this.SendPropertyChanging();
					this._Zip = value;
					this.SendPropertyChanged("Zip");
					this.OnZipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Attn", DbType="VarChar(20)")]
		public string Attn
		{
			get
			{
				return this._Attn;
			}
			set
			{
				if ((this._Attn != value))
				{
					this.OnAttnChanging(value);
					this.SendPropertyChanging();
					this._Attn = value;
					this.SendPropertyChanged("Attn");
					this.OnAttnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="VarChar(15)")]
		public string Phone
		{
			get
			{
				return this._Phone;
			}
			set
			{
				if ((this._Phone != value))
				{
					this.OnPhoneChanging(value);
					this.SendPropertyChanging();
					this._Phone = value;
					this.SendPropertyChanged("Phone");
					this.OnPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fax", DbType="VarChar(15)")]
		public string Fax
		{
			get
			{
				return this._Fax;
			}
			set
			{
				if ((this._Fax != value))
				{
					this.OnFaxChanging(value);
					this.SendPropertyChanging();
					this._Fax = value;
					this.SendPropertyChanged("Fax");
					this.OnFaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMail", DbType="VarChar(40)")]
		public string EMail
		{
			get
			{
				return this._EMail;
			}
			set
			{
				if ((this._EMail != value))
				{
					this.OnEMailChanging(value);
					this.SendPropertyChanging();
					this._EMail = value;
					this.SendPropertyChanged("EMail");
					this.OnEMailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Budget", DbType="Money")]
		public System.Nullable<decimal> Budget
		{
			get
			{
				return this._Budget;
			}
			set
			{
				if ((this._Budget != value))
				{
					this.OnBudgetChanging(value);
					this.SendPropertyChanging();
					this._Budget = value;
					this.SendPropertyChanged("Budget");
					this.OnBudgetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JobTotal", DbType="Money")]
		public System.Nullable<decimal> JobTotal
		{
			get
			{
				return this._JobTotal;
			}
			set
			{
				if ((this._JobTotal != value))
				{
					this.OnJobTotalChanging(value);
					this.SendPropertyChanging();
					this._JobTotal = value;
					this.SendPropertyChanged("JobTotal");
					this.OnJobTotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaxDefault", DbType="VarChar(1)")]
		public string TaxDefault
		{
			get
			{
				return this._TaxDefault;
			}
			set
			{
				if ((this._TaxDefault != value))
				{
					this.OnTaxDefaultChanging(value);
					this.SendPropertyChanging();
					this._TaxDefault = value;
					this.SendPropertyChanged("TaxDefault");
					this.OnTaxDefaultChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Schedule", DbType="VarChar(5)")]
		public string Schedule
		{
			get
			{
				return this._Schedule;
			}
			set
			{
				if ((this._Schedule != value))
				{
					this.OnScheduleChanging(value);
					this.SendPropertyChanging();
					this._Schedule = value;
					this.SendPropertyChanged("Schedule");
					this.OnScheduleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaxID", DbType="VarChar(15)")]
		public string TaxID
		{
			get
			{
				return this._TaxID;
			}
			set
			{
				if ((this._TaxID != value))
				{
					this.OnTaxIDChanging(value);
					this.SendPropertyChanging();
					this._TaxID = value;
					this.SendPropertyChanged("TaxID");
					this.OnTaxIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaxRate", DbType="Float")]
		public System.Nullable<double> TaxRate
		{
			get
			{
				return this._TaxRate;
			}
			set
			{
				if ((this._TaxRate != value))
				{
					this.OnTaxRateChanging(value);
					this.SendPropertyChanging();
					this._TaxRate = value;
					this.SendPropertyChanged("TaxRate");
					this.OnTaxRateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POMsg", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string POMsg
		{
			get
			{
				return this._POMsg;
			}
			set
			{
				if ((this._POMsg != value))
				{
					this.OnPOMsgChanging(value);
					this.SendPropertyChanging();
					this._POMsg = value;
					this.SendPropertyChanged("POMsg");
					this.OnPOMsgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Company", DbType="VarChar(3)")]
		public string Company
		{
			get
			{
				return this._Company;
			}
			set
			{
				if ((this._Company != value))
				{
					this.OnCompanyChanging(value);
					this.SendPropertyChanging();
					this._Company = value;
					this.SendPropertyChanged("Company");
					this.OnCompanyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Division", DbType="VarChar(3)")]
		public string Division
		{
			get
			{
				return this._Division;
			}
			set
			{
				if ((this._Division != value))
				{
					this.OnDivisionChanging(value);
					this.SendPropertyChanging();
					this._Division = value;
					this.SendPropertyChanged("Division");
					this.OnDivisionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CostCtr", DbType="Float")]
		public System.Nullable<double> CostCtr
		{
			get
			{
				return this._CostCtr;
			}
			set
			{
				if ((this._CostCtr != value))
				{
					this.OnCostCtrChanging(value);
					this.SendPropertyChanging();
					this._CostCtr = value;
					this.SendPropertyChanged("CostCtr");
					this.OnCostCtrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Act", DbType="Char(1)")]
		public string Act
		{
			get
			{
				return this._Act;
			}
			set
			{
				if ((this._Act != value))
				{
					this.OnActChanging(value);
					this.SendPropertyChanging();
					this._Act = value;
					this.SendPropertyChanged("Act");
					this.OnActChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PurchasingMsg", DbType="VarChar(2000)")]
		public string PurchasingMsg
		{
			get
			{
				return this._PurchasingMsg;
			}
			set
			{
				if ((this._PurchasingMsg != value))
				{
					this.OnPurchasingMsgChanging(value);
					this.SendPropertyChanging();
					this._PurchasingMsg = value;
					this.SendPropertyChanged("PurchasingMsg");
					this.OnPurchasingMsgChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.JobPhase")]
	public partial class JobPhase : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Job;
		
		private string _Phase;
		
		private string _Description;
		
		private string _Act;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnJobChanging(string value);
    partial void OnJobChanged();
    partial void OnPhaseChanging(string value);
    partial void OnPhaseChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnActChanging(string value);
    partial void OnActChanged();
    #endregion
		
		public JobPhase()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Job", DbType="VarChar(12) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Job
		{
			get
			{
				return this._Job;
			}
			set
			{
				if ((this._Job != value))
				{
					this.OnJobChanging(value);
					this.SendPropertyChanging();
					this._Job = value;
					this.SendPropertyChanged("Job");
					this.OnJobChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phase", DbType="VarChar(2) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Phase
		{
			get
			{
				return this._Phase;
			}
			set
			{
				if ((this._Phase != value))
				{
					this.OnPhaseChanging(value);
					this.SendPropertyChanging();
					this._Phase = value;
					this.SendPropertyChanged("Phase");
					this.OnPhaseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(30)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Act", DbType="Char(1)")]
		public string Act
		{
			get
			{
				return this._Act;
			}
			set
			{
				if ((this._Act != value))
				{
					this.OnActChanging(value);
					this.SendPropertyChanging();
					this._Act = value;
					this.SendPropertyChanged("Act");
					this.OnActChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.JobPhCcd")]
	public partial class JobPhCcd : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Job;
		
		private string _Phase;
		
		private string _CostCode;
		
		private string _Description;
		
		private string _Act;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnJobChanging(string value);
    partial void OnJobChanged();
    partial void OnPhaseChanging(string value);
    partial void OnPhaseChanged();
    partial void OnCostCodeChanging(string value);
    partial void OnCostCodeChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnActChanging(string value);
    partial void OnActChanged();
    #endregion
		
		public JobPhCcd()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Job", DbType="VarChar(12) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Job
		{
			get
			{
				return this._Job;
			}
			set
			{
				if ((this._Job != value))
				{
					this.OnJobChanging(value);
					this.SendPropertyChanging();
					this._Job = value;
					this.SendPropertyChanged("Job");
					this.OnJobChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phase", DbType="VarChar(2) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Phase
		{
			get
			{
				return this._Phase;
			}
			set
			{
				if ((this._Phase != value))
				{
					this.OnPhaseChanging(value);
					this.SendPropertyChanging();
					this._Phase = value;
					this.SendPropertyChanged("Phase");
					this.OnPhaseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CostCode", DbType="VarChar(9) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CostCode
		{
			get
			{
				return this._CostCode;
			}
			set
			{
				if ((this._CostCode != value))
				{
					this.OnCostCodeChanging(value);
					this.SendPropertyChanging();
					this._CostCode = value;
					this.SendPropertyChanged("CostCode");
					this.OnCostCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(35)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Act", DbType="Char(1)")]
		public string Act
		{
			get
			{
				return this._Act;
			}
			set
			{
				if ((this._Act != value))
				{
					this.OnActChanging(value);
					this.SendPropertyChanging();
					this._Act = value;
					this.SendPropertyChanged("Act");
					this.OnActChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.COINSESB_WBS")]
	public partial class COINSESB_WB : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Job;
		
		private string _WB_Code;
		
		private string _WB_Desc;
		
		private string _Section;
		
		private string _Activity;
		
		private System.Nullable<bool> _UsesActivity;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnJobChanging(string value);
    partial void OnJobChanged();
    partial void OnWB_CodeChanging(string value);
    partial void OnWB_CodeChanged();
    partial void OnWB_DescChanging(string value);
    partial void OnWB_DescChanged();
    partial void OnSectionChanging(string value);
    partial void OnSectionChanged();
    partial void OnActivityChanging(string value);
    partial void OnActivityChanged();
    partial void OnUsesActivityChanging(System.Nullable<bool> value);
    partial void OnUsesActivityChanged();
    #endregion
		
		public COINSESB_WB()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Job", DbType="VarChar(12) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Job
		{
			get
			{
				return this._Job;
			}
			set
			{
				if ((this._Job != value))
				{
					this.OnJobChanging(value);
					this.SendPropertyChanging();
					this._Job = value;
					this.SendPropertyChanged("Job");
					this.OnJobChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WB_Code", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string WB_Code
		{
			get
			{
				return this._WB_Code;
			}
			set
			{
				if ((this._WB_Code != value))
				{
					this.OnWB_CodeChanging(value);
					this.SendPropertyChanging();
					this._WB_Code = value;
					this.SendPropertyChanged("WB_Code");
					this.OnWB_CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WB_Desc", DbType="VarChar(50)")]
		public string WB_Desc
		{
			get
			{
				return this._WB_Desc;
			}
			set
			{
				if ((this._WB_Desc != value))
				{
					this.OnWB_DescChanging(value);
					this.SendPropertyChanging();
					this._WB_Desc = value;
					this.SendPropertyChanged("WB_Desc");
					this.OnWB_DescChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Section", DbType="VarChar(50)")]
		public string Section
		{
			get
			{
				return this._Section;
			}
			set
			{
				if ((this._Section != value))
				{
					this.OnSectionChanging(value);
					this.SendPropertyChanging();
					this._Section = value;
					this.SendPropertyChanged("Section");
					this.OnSectionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Activity", DbType="VarChar(50)")]
		public string Activity
		{
			get
			{
				return this._Activity;
			}
			set
			{
				if ((this._Activity != value))
				{
					this.OnActivityChanging(value);
					this.SendPropertyChanging();
					this._Activity = value;
					this.SendPropertyChanged("Activity");
					this.OnActivityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsesActivity", DbType="Bit")]
		public System.Nullable<bool> UsesActivity
		{
			get
			{
				return this._UsesActivity;
			}
			set
			{
				if ((this._UsesActivity != value))
				{
					this.OnUsesActivityChanging(value);
					this.SendPropertyChanging();
					this._UsesActivity = value;
					this.SendPropertyChanged("UsesActivity");
					this.OnUsesActivityChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.WO")]
	public partial class WO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _WO1;
		
		private string _WorkType;
		
		private bool _Contract;
		
		private string _Company;
		
		private string _Division;
		
		private System.Nullable<double> _CostCtr;
		
		private System.Nullable<double> _TaxRate;
		
		private string _Customer;
		
		private string _Site;
		
		private string _SiteName;
		
		private string _Act;
		
		private string _SiteAdd1;
		
		private string _SiteAdd2;
		
		private string _SiteCity;
		
		private string _SiteState;
		
		private string _SiteZip;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnWO1Changing(string value);
    partial void OnWO1Changed();
    partial void OnWorkTypeChanging(string value);
    partial void OnWorkTypeChanged();
    partial void OnContractChanging(bool value);
    partial void OnContractChanged();
    partial void OnCompanyChanging(string value);
    partial void OnCompanyChanged();
    partial void OnDivisionChanging(string value);
    partial void OnDivisionChanged();
    partial void OnCostCtrChanging(System.Nullable<double> value);
    partial void OnCostCtrChanged();
    partial void OnTaxRateChanging(System.Nullable<double> value);
    partial void OnTaxRateChanged();
    partial void OnCustomerChanging(string value);
    partial void OnCustomerChanged();
    partial void OnSiteChanging(string value);
    partial void OnSiteChanged();
    partial void OnSiteNameChanging(string value);
    partial void OnSiteNameChanged();
    partial void OnActChanging(string value);
    partial void OnActChanged();
    partial void OnSiteAdd1Changing(string value);
    partial void OnSiteAdd1Changed();
    partial void OnSiteAdd2Changing(string value);
    partial void OnSiteAdd2Changed();
    partial void OnSiteCityChanging(string value);
    partial void OnSiteCityChanged();
    partial void OnSiteStateChanging(string value);
    partial void OnSiteStateChanged();
    partial void OnSiteZipChanging(string value);
    partial void OnSiteZipChanged();
    #endregion
		
		public WO()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="WO", Storage="_WO1", DbType="VarChar(12) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string WO1
		{
			get
			{
				return this._WO1;
			}
			set
			{
				if ((this._WO1 != value))
				{
					this.OnWO1Changing(value);
					this.SendPropertyChanging();
					this._WO1 = value;
					this.SendPropertyChanged("WO1");
					this.OnWO1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WorkType", DbType="VarChar(1)")]
		public string WorkType
		{
			get
			{
				return this._WorkType;
			}
			set
			{
				if ((this._WorkType != value))
				{
					this.OnWorkTypeChanging(value);
					this.SendPropertyChanging();
					this._WorkType = value;
					this.SendPropertyChanged("WorkType");
					this.OnWorkTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contract", DbType="Bit NOT NULL")]
		public bool Contract
		{
			get
			{
				return this._Contract;
			}
			set
			{
				if ((this._Contract != value))
				{
					this.OnContractChanging(value);
					this.SendPropertyChanging();
					this._Contract = value;
					this.SendPropertyChanged("Contract");
					this.OnContractChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Company", DbType="VarChar(3)")]
		public string Company
		{
			get
			{
				return this._Company;
			}
			set
			{
				if ((this._Company != value))
				{
					this.OnCompanyChanging(value);
					this.SendPropertyChanging();
					this._Company = value;
					this.SendPropertyChanged("Company");
					this.OnCompanyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Division", DbType="VarChar(3)")]
		public string Division
		{
			get
			{
				return this._Division;
			}
			set
			{
				if ((this._Division != value))
				{
					this.OnDivisionChanging(value);
					this.SendPropertyChanging();
					this._Division = value;
					this.SendPropertyChanged("Division");
					this.OnDivisionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CostCtr", DbType="Float")]
		public System.Nullable<double> CostCtr
		{
			get
			{
				return this._CostCtr;
			}
			set
			{
				if ((this._CostCtr != value))
				{
					this.OnCostCtrChanging(value);
					this.SendPropertyChanging();
					this._CostCtr = value;
					this.SendPropertyChanged("CostCtr");
					this.OnCostCtrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaxRate", DbType="Float")]
		public System.Nullable<double> TaxRate
		{
			get
			{
				return this._TaxRate;
			}
			set
			{
				if ((this._TaxRate != value))
				{
					this.OnTaxRateChanging(value);
					this.SendPropertyChanging();
					this._TaxRate = value;
					this.SendPropertyChanged("TaxRate");
					this.OnTaxRateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Customer", DbType="VarChar(8)")]
		public string Customer
		{
			get
			{
				return this._Customer;
			}
			set
			{
				if ((this._Customer != value))
				{
					this.OnCustomerChanging(value);
					this.SendPropertyChanging();
					this._Customer = value;
					this.SendPropertyChanged("Customer");
					this.OnCustomerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Site", DbType="VarChar(4)")]
		public string Site
		{
			get
			{
				return this._Site;
			}
			set
			{
				if ((this._Site != value))
				{
					this.OnSiteChanging(value);
					this.SendPropertyChanging();
					this._Site = value;
					this.SendPropertyChanged("Site");
					this.OnSiteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SiteName", DbType="VarChar(30)")]
		public string SiteName
		{
			get
			{
				return this._SiteName;
			}
			set
			{
				if ((this._SiteName != value))
				{
					this.OnSiteNameChanging(value);
					this.SendPropertyChanging();
					this._SiteName = value;
					this.SendPropertyChanged("SiteName");
					this.OnSiteNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Act", DbType="Char(1)")]
		public string Act
		{
			get
			{
				return this._Act;
			}
			set
			{
				if ((this._Act != value))
				{
					this.OnActChanging(value);
					this.SendPropertyChanging();
					this._Act = value;
					this.SendPropertyChanged("Act");
					this.OnActChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SiteAdd1", DbType="Char(30)")]
		public string SiteAdd1
		{
			get
			{
				return this._SiteAdd1;
			}
			set
			{
				if ((this._SiteAdd1 != value))
				{
					this.OnSiteAdd1Changing(value);
					this.SendPropertyChanging();
					this._SiteAdd1 = value;
					this.SendPropertyChanged("SiteAdd1");
					this.OnSiteAdd1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SiteAdd2", DbType="Char(30)")]
		public string SiteAdd2
		{
			get
			{
				return this._SiteAdd2;
			}
			set
			{
				if ((this._SiteAdd2 != value))
				{
					this.OnSiteAdd2Changing(value);
					this.SendPropertyChanging();
					this._SiteAdd2 = value;
					this.SendPropertyChanged("SiteAdd2");
					this.OnSiteAdd2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SiteCity", DbType="Char(15)")]
		public string SiteCity
		{
			get
			{
				return this._SiteCity;
			}
			set
			{
				if ((this._SiteCity != value))
				{
					this.OnSiteCityChanging(value);
					this.SendPropertyChanging();
					this._SiteCity = value;
					this.SendPropertyChanged("SiteCity");
					this.OnSiteCityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SiteState", DbType="Char(4)")]
		public string SiteState
		{
			get
			{
				return this._SiteState;
			}
			set
			{
				if ((this._SiteState != value))
				{
					this.OnSiteStateChanging(value);
					this.SendPropertyChanging();
					this._SiteState = value;
					this.SendPropertyChanged("SiteState");
					this.OnSiteStateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SiteZip", DbType="Char(15)")]
		public string SiteZip
		{
			get
			{
				return this._SiteZip;
			}
			set
			{
				if ((this._SiteZip != value))
				{
					this.OnSiteZipChanging(value);
					this.SendPropertyChanging();
					this._SiteZip = value;
					this.SendPropertyChanged("SiteZip");
					this.OnSiteZipChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
